### ISSUE TITLE
[1.12] Facades does not working with modded block like Chisel or TechGun blocks

### ISSUE THREAD

**Issue by hron84** [CyclopsMC/IntegratedDynamics#1021]
Every time I try to place down a facade that is camouflaged with a Chisel or TechGuns block I get silent CCL crashes (it does not actually crashes the game, but instead says "CCL caught and exception rendering a block. See the log for info"

And the log says

```
net.minecraft.util.ReportedException: Tesselating block model
        at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:95) ~[bvm.class:?]
        at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:82) [CCBlockRendererDispatcher.class:?]
        at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:200) [bxr.class:?]
        at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100) [bxn.class:?]
        at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(ChunkRenderDispatcher.java:172) [bxm.class:?]
        at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:976) [buy.class:?]
        at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1316) [buq.class:?]
        at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259) [buq.class:?]
        at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062) [buq.class:?]
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119) [bib.class:?]
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
        at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_242]
        at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_242]
        at org.cyclops.integrateddynamics.client.model.CableModelBase.getFacadeQuads(CableModelBase.java:140) ~[CableModelBase.class:?]
        at org.cyclops.integrateddynamics.client.model.CableModelBase.getGeneralQuads(CableModelBase.java:275) ~[CableModelBase.class:?]
        at org.cyclops.cyclopscore.client.model.DynamicItemAndBlockModel.func_188616_a(DynamicItemAndBlockModel.java:52) ~[DynamicItemAndBlockModel.class:?]
        at org.cyclops.cyclopscore.client.model.DynamicItemAndBlockModel.func_188616_a(DynamicItemAndBlockModel.java:49) ~[DynamicItemAndBlockModel.class:?]
        at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:95) ~[ForgeBlockModelRenderer.class:?]
        at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:81) ~[ForgeBlockModelRenderer.class:?]
        at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:47) ~[bvo.class:?]
        at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:38) ~[bvo.class:?]
        at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80) ~[bvm.class:?]
        ... 17 more
```
#### Versions:

- Mod versions: 
  - Integrated Dynamics 1.1.11
  - Chisel 1.0.2.45
  - TechGuns 2.0.2.0_pre3.2
- Minecraft: 1.12.2
- Forge: 14.23.5.2855

**Comment by hron84** [comment]
My wild guessing is a problem with connected textures, as both Chisel's Factory block and TechGuns blocks does support CTM.
It would be fine for me if the facade just don't support the connected texture and displays a single texture (just like how StorageDrawers' framed blocks handles this situation) as I know very well supporting CT is not an easy job. But a render crash and a totally transparent block is something that could be better.

**Comment by rubensworks** [comment]
Unfortunately, 1.12 is not supported anymore.
I recommend either updating, or not facading those blocks.

**Comment by hron84** [comment]
@rubensworks TechGuns and also the modpack I playing with is not out for anything newer than 1.12....
