### ISSUE TITLE
Server hardlock on putting scripted card from "Place Item Entity" into "Place Item Entities" on World Item Exporter

### ISSUE THREAD

**Issue by antofdeath** [CyclopsMC/IntegratedDynamics#1027]
So if the script is required I can go grab it, but it's based on placing a card in the wrong spot and leading to a crash instead of a catch-error. The server also can not resolve, thus leading to a restart loop, had to back up to previous save. Happens again on recreation.

https://cdn.discordapp.com/attachments/386054223688630272/834997796460691476/unknown.png

The conditions of the setup are bsed on the "Volcano block" modpack, with IntegratedDynamics-1.12.2-1.1.11.jar as the mod version. In this situation, a cycling loop based on list length for items in the Botania petalpond chooses what items to drop into the world using a World Item Exporter. 

https://cdn.discordapp.com/attachments/386054223688630272/834997108309491712/unknown.png 

Is a example of the set up that lead to this condition.

https://cdn.discordapp.com/attachments/386054223688630272/834997226853761024/unknown.png The input items
https://cdn.discordapp.com/attachments/386054223688630272/834997262999617607/unknown.png Recipe output

Running theory is somethiing to do with expecting a item and getting a integer value.

Heres the server error dump.
:
Description: Exception in server tick loop

java.lang.ClassCastException: org.cyclops.integrateddynamics.core.evaluate.variable.ValueObjectTypeItemStack$ValueItemStack cannot be cast to org.cyclops.integrateddynamics.core.evaluate.variable.ValueTypeInteger$ValueInteger
    at org.cyclops.integrateddynamics.part.aspect.write.AspectWriteBuilders.lambda$static$1(AspectWriteBuilders.java:72)
    at org.cyclops.integrateddynamics.core.part.aspect.build.AspectBuilder$BuiltWriter.write(AspectBuilder.java:429)
    at org.cyclops.integrateddynamics.part.aspect.write.AspectWriteBase.update(AspectWriteBase.java:59)
    at org.cyclops.integrateddynamics.core.part.aspect.build.AspectBuilder$BuiltWriter.update(AspectBuilder.java:452)
    at org.cyclops.integrateddynamics.core.part.write.PartTypeWriteBase.update(PartTypeWriteBase.java:96)
    at org.cyclops.integrateddynamics.core.part.write.PartTypeWriteBase.update(PartTypeWriteBase.java:48)
    at org.cyclops.integrateddynamics.core.network.PartNetworkElement.update(PartNetworkElement.java:135)
    at org.cyclops.integrateddynamics.core.network.Network.update(Network.java:410)
    at org.cyclops.integrateddynamics.core.TickHandler.onTick(TickHandler.java:65)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_728_TickHandler_onTick_TickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)

**Comment by rubensworks** [comment]
> with IntegratedDynamics-1.12.2-1.1.11.jar

Unfortunately MC 1.12 is not supported anymore.
Feel free to reopen if you can reproduce in a 1.16 version.
