### ISSUE TITLE
Cardboard box causes crash

### ISSUE THREAD

**Issue by draxxris** [CyclopsMC/IntegratedDynamics#1139]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Server crash when placing a cardboard box over a configured Item Exporter

#### Steps to reproduce the problem:

1. Put down an ID pipe
2. Attach Item Exporter
3. Configure Item Exporter to be always extract via Boolean card
4. Place (right click) an empty Mekanism cardbard box over said item exporter

#### Expected behaviour:

Not sure exactly, maybe just destroy the tile entity at the location the cardboard box was placed? Don't really want the onus to be on ID developers to fix this, but crashing the entire server should be non-preferred, especially if playing with other people on it.

____

#### Versions:

Mod:
```
IntegratedCrafting-1.16.5-1.0.20.jar
IntegratedDynamics-1.16.5-1.10.7.jar
IntegratedTerminals-1.16.5-1.2.12.jar
IntegratedTunnels-1.16.5-1.8.9.jar
```

Minecraft: 1.16.5

Forge: 36.2.26

#### Log file:

```
java.lang.IllegalStateException: Could not find a part container at DimPos(world=minecraft:overworld, blockPos=BlockPos{x=-1422, y=102, z=-1577}, worldReference=null)
        at org.cyclops.integrateddynamics.core.helper.PartHelpers.lambda$getPartContainerChecked$1(PartHelpers.java:103) ~[?:1.10.7] {re:classloading}
        at net.minecraftforge.common.util.LazyOptional.orElseThrow(LazyOptional.java:296) ~[?:?] {re:mixin,re:classloading}
        at org.cyclops.integrateddynamics.core.helper.PartHelpers.getPartContainerChecked(PartHelpers.java:103) ~[?:1.10.7] {re:classloading}
        at org.cyclops.integrateddynamics.core.network.PartNetworkElement.getPartContainer(PartNetworkElement.java:82) ~[?:1.10.7] {re:classloading}
        at org.cyclops.integrateddynamics.core.network.PartNetworkElement.hasPartState(PartNetworkElement.java:119) ~[?:1.10.7] {re:classloading}
        at org.cyclops.integrateddynamics.core.network.PartNetworkElement.getPriority(PartNetworkElement.java:93) ~[?:1.10.7] {re:classloading}
        at org.cyclops.integrateddynamics.core.network.PartNetworkElement.compareTo(PartNetworkElement.java:239) ~[?:1.10.7] {re:classloading}
        at org.cyclops.integrateddynamics.core.network.PartNetworkElement.compareTo(PartNetworkElement.java:33) ~[?:1.10.7] {re:classloading}
        at java.util.TreeMap.getEntry(TreeMap.java:352) ~[?:1.8.0_112] {}
        at java.util.TreeMap.get(TreeMap.java:278) ~[?:1.8.0_112] {}
        at java.util.Map.getOrDefault(Map.java:588) ~[?:1.8.0_112] {}
        at org.cyclops.integrateddynamics.core.network.Network.update(Network.java:406) ~[?:1.10.7] {re:classloading}
        at org.cyclops.integrateddynamics.core.TickHandler.onTick(TickHandler.java:73) ~[?:1.10.7] {re:classloading}
        at net.minecraftforge.eventbus.ASMEventHandler_1994_TickHandler_onTick_TickEvent.invoke(.dynamic) ~[?:?] {}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
```

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Yeah, ID has no dedicated support for block-moving mods. So a crash is to be expected.
