### ISSUE TITLE
[master-1.18 f9d482e] Facade Rendering Crash

### ISSUE THREAD

**Issue by met4000** [CyclopsMC/IntegratedDynamics#1157]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Game crashes, whenever a facade is attempted to be rendered.

#### Steps to reproduce the problem:

1. build and launch client (done with forgegradle generated `runClient` eclipse launch)
2. load into a world (dev world used)
3. open the InDy creative tab, or search for facade in the creative search menu, or otherwise cause the facade to appear on-screen

#### Expected behaviour:

Facade is rendered and no crash.

____

#### Versions:

- This mod: f9d482e (master-1.18 head, as of time of writing)
- Minecraft: 1.18.2 (i.e. based on f9d482e [gradle.properties])
- Forge: 40.0.54 (i.e. based on f9d482e [gradle.properties])

#### Log file:

Crash Report: https://pastebin.com/raw/967wt5QH

Notable line(s):
```
java.lang.StackOverflowError: Rendering item
	at org.cyclops.integrateddynamics.client.render.model.FacadeModel.getGeneralQuads(FacadeModel.java:53) ~[%2381!/:?] {re:classloading}
	at org.cyclops.cyclopscore.client.model.DynamicItemAndBlockModel.getQuads(DynamicItemAndBlockModel.java:63) ~[cyclopscore-1.18.2-1.13.4-158-deobf.jar%2383!/:1.13.4] {re:classloading}
	at org.cyclops.cyclopscore.client.model.DynamicItemAndBlockModel.getQuads(DynamicItemAndBlockModel.java:45) ~[cyclopscore-1.18.2-1.13.4-158-deobf.jar%2383!/:1.13.4] {re:classloading}
	at org.cyclops.integrateddynamics.client.render.model.FacadeModel.getGeneralQuads(FacadeModel.java:55) ~[%2381!/:?] {re:classloading}
	at org.cyclops.cyclopscore.client.model.DynamicItemAndBlockModel.getQuads(DynamicItemAndBlockModel.java:63) ~[cyclopscore-1.18.2-1.13.4-158-deobf.jar%2383!/:1.13.4] {re:classloading}
	at org.cyclops.cyclopscore.client.model.DynamicItemAndBlockModel.getQuads(DynamicItemAndBlockModel.java:45) ~[cyclopscore-1.18.2-1.13.4-158-deobf.jar%2383!/:1.13.4] {re:classloading}
	at org.cyclops.integrateddynamics.client.render.model.FacadeModel.getGeneralQuads(FacadeModel.java:55) ~[%2381!/:?] {re:classloading}
	at org.cyclops.cyclopscore.client.model.DynamicItemAndBlockModel.getQuads(DynamicItemAndBlockModel.java:63) ~[cyclopscore-1.18.2-1.13.4-158-deobf.jar%2383!/:1.13.4] {re:classloading}
	at org.cyclops.cyclopscore.client.model.DynamicItemAndBlockModel.getQuads(DynamicItemAndBlockModel.java:45) ~[cyclopscore-1.18.2-1.13.4-158-deobf.jar%2383!/:1.13.4] {re:classloading}
	at org.cyclops.integrateddynamics.client.render.model.FacadeModel.getGeneralQuads(FacadeModel.java:55) ~[%2381!/:?] {re:classloading}
	at org.cyclops.cyclopscore.client.model.DynamicItemAndBlockModel.getQuads(DynamicItemAndBlockModel.java:63) ~[cyclopscore-1.18.2-1.13.4-158-deobf.jar%2383!/:1.13.4] {re:classloading}
	at org.cyclops.cyclopscore.client.model.DynamicItemAndBlockModel.getQuads(DynamicItemAndBlockModel.java:45) ~[cyclopscore-1.18.2-1.13.4-158-deobf.jar%2383!/:1.13.4] {re:classloading}
```

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Ok, can confirm the problem.
It seems to be 1.18.2-only (which is a good thing).
