### ISSUE TITLE
[1.18.2] Failed to load JEI compat

### ISSUE THREAD

**Issue by Chaos02** [CyclopsMC/IntegratedDynamics#1203]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Failed to load JEI compat

#### Steps to reproduce the problem:

start game

____

#### Versions:

- This mod: 1.11.8
- Minecraft: 1.18.2
- Forge: 40.1.73
- JEI: 9.7.1-232 (v9 essential for FLUID crafting)

I am a modpack author.

#### Log file:

```
[Render thread/ERROR] [mezz.jei.forge.util.AnnotatedInstanceUtil/]: Failed to load: org.cyclops.integrateddynamicscompat.modcompat.jei.JEIIntegratedDynamicsConfig
java.lang.NoClassDefFoundError: mezz/jei/forge/platform/PlatformHelper
	at org.cyclops.integrateddynamicscompat.modcompat.jei.JEIIntegratedDynamicsConfig.<clinit>(JEIIntegratedDynamicsConfig.java:47) ~[IntegratedDynamics-1.18.2-1.11.8.jar%23240!/:1.11.8]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at mezz.jei.forge.util.AnnotatedInstanceUtil.getInstances(AnnotatedInstanceUtil.java:47) ~[jei-1.18.2-9.7.1.232.jar%23251!/:9.7.1.232]
	at mezz.jei.forge.util.AnnotatedInstanceUtil.getModPlugins(AnnotatedInstanceUtil.java:27) ~[jei-1.18.2-9.7.1.232.jar%23251!/:9.7.1.232]
	at mezz.jei.forge.startup.ClientLifecycleHandler.<init>(ClientLifecycleHandler.java:74) ~[jei-1.18.2-9.7.1.232.jar%23251!/:9.7.1.232]
	at mezz.jei.forge.JustEnoughItemsClient.onRegisterReloadListenerEvent(JustEnoughItemsClient.java:39) ~[jei-1.18.2-9.7.1.232.jar%23251!/:9.7.1.232]
	at mezz.jei.forge.JustEnoughItemsClient.lambda$register$0(JustEnoughItemsClient.java:28) ~[jei-1.18.2-9.7.1.232.jar%23251!/:9.7.1.232]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[javafmllanguage-1.18.2-40.1.73.jar%23411!/:?]
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$31(ModLoader.java:285) ~[fmlcore-1.18.2-40.1.73.jar%23410!/:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:219) ~[fmlcore-1.18.2-40.1.73.jar%23410!/:?]
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:285) ~[fmlcore-1.18.2-40.1.73.jar%23410!/:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:537) ~[client-1.18.2-20220404.173914-srg.jar%23409!/:?]
	at net.minecraft.client.main.Main.main(Main.java:169) ~[client-1.18.2-20220404.173914-srg.jar%23409!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.73.jar%2317!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
Caused by: java.lang.ClassNotFoundException: mezz.jei.forge.platform.PlatformHelper
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:138) ~[securejarhandler-1.0.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 32 more
```

Log split in three (2000L per paste) cause of size.
[https://pastebin.com/BJTLggHu](https://www.curseforge.com/linkout?remoteUrl=https%253a%252f%252fpastebin.com%252fBJTLggHu)
https://pastebin.com/Z7x8ND2G
https://pastebin.com/7srNdudh

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
ID 1.11.8 requires JEI of version 10.x, so updating JEI will fix your problem.
If you can't update JEI, please downgrade ID to the previous version.
