### ISSUE TITLE
Squeezer crashes the game

### ISSUE THREAD

**Issue by valipopescu** [CyclopsMC/IntegratedDynamics#1282]
#### Issue type:

- :bug: Bug 

____

#### Short description:

The squeezer crashes the game shortly after using it or loading into a world having it. 
The crash reports :
```
java.lang.IllegalArgumentException: Cannot get property IntegerProperty{name=height, clazz=class java.lang.Integer, values=[1, 2, 3, 4, 5, 6, 7]} as it does not exist in Block{minecraft:air}
	at net.minecraft.world.level.block.state.StateHolder.m_61143_(StateHolder.java:98) ~[client-1.20.1-20230612.114412-srg.jar%23582!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ferritecore.fastmap.mixin.json:FastMapStateHolderMixin,pl:mixin:A}
	at org.cyclops.integrateddynamics.block.BlockSqueezer.getRelativeTopPositionTop(BlockSqueezer.java:174) ~[IntegratedDynamics-1.20.1-1.16.7.jar%23464!/:1.16.7] {re:classloading}
	at org.cyclops.integrateddynamics.block.BlockSqueezer.m_5548_(BlockSqueezer.java:144) ~[IntegratedDynamics-1.20.1-1.16.7.jar%23464!/:1.16.7] {re:classloading}
	at net.minecraft.world.entity.Entity.m_6478_(Entity.java:672) ~[client-1.20.1-20230612.114412-srg.jar%23582!/:?] 
```	

#### Steps to reproduce the problem:

1. Make a normal squeezer,
2. Squeeze a bunch of items (menril wood for crystalized menril)
3. crash
4. Load up the game again
5. crash shortly after loading.

Mention the game did not crash on the first time putting the squeezer down. It only crashed when taking it and putting it down again as I miscalculated how much menril will I need.

#### Expected behaviour:

Should just not crash.

____

#### Versions:

- This mod: Integrated Dynamics 1.16.7 for Minecraft 1.20.1
- Minecraft: 1.20.1
- Forge: 47.0.35

#### Log file:
https://pastebin.com/pyHmFwZw

**Comment by rubensworks** [comment]
Thanks for reporting!
