### ISSUE TITLE
Random client crash

### ISSUE THREAD

**Issue by rubensworks** [CyclopsMC/IntegratedDynamics#13]
Something with models...

```
java.lang.NullPointerException: Tesselating block model
    at org.cyclops.integrateddynamics.client.model.CableModel.getPartModel(CableModel.java:67)
    at org.cyclops.integrateddynamics.client.model.CableModelBase.func_177550_a(CableModelBase.java:157)
    at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:88)
    at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_178258_b(ForgeBlockModelRenderer.java:53)
    at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:40)
    at net.minecraft.client.renderer.BlockModelRenderer.func_178259_a(BlockModelRenderer.java:30)
    at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:94)
    at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:194)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:78)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:38)
    at java.lang.Thread.run(Thread.java:745)
```

Also:

```
java.lang.NullPointerException: Tesselating block in world
at org.cyclops.integrateddynamics.core.tileentity.TileMultipartTicking.getConnectionState(TileMultipartTicking.java:259)
```

**Comment by rubensworks** [comment]
Latest release (0.3.3) should've fixed this. I'll leave this open for a while, just in case it isn't fixed.
