### ISSUE TITLE
Repeated crash/visual issues when placing Facade of type Logic Cable on another Logic Cable

### ISSUE THREAD

**Issue by laundmo** [CyclopsMC/IntegratedDynamics#1334]
#### Issue type:

- :bug: Bug 

____

#### Short description:

A "Facade - Logic Cable" (crafting a facade with a logic cable) causes missing textures and crashing (multiplayer) or immediately crashing (singleplayer).

Crashes client in multiplayer when:
- placing 
- causing a update to
- breaking (crashes before its broken)

#### Steps to reproduce the problem:

1. craft a facade with a logic cable, producing a "Facade - Logic Cable"
2. Place the facade on a logic cable
3. crash

option 1: TNP Limitless 6
5. restart game
6. notice no block textures loading - except things like torches, itemframes, etc.
7. attempt to break facade or surrounding blocks
8. crash again

option 2: singleplayer 1.20.1, just IntegratedDynamics
5. restart game
6. load world
7. crash again

#### Expected behaviour:

Facades should not be craft-able with incompatible blocks
____

#### Versions:
first encountered in modpack: TNP Limitless 6
 
- This mod: 1.20.0
- Minecraft: 1.19.2
- Forge: 43.2.21

Recreated with following versions (newest as of writing)
- This mod: 1.21.1
- Minecraft: 1.20.1
- Forge: 47.2.21
- Cyclops Core: 1.19.0
- CommonCapabilities: 2.9.1

#### Log file:
first crash when placing facade on cable: https://share.yadamiel.com/minecraft-integrateddynamics-crash.log
crash when loading in singleplayer: https://share.yadamiel.com/minecraft-integrateddynamics-crash2.log

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by laundmo** [comment]
How to fix: i was able to use the ftbbackups mod backup to replace the specific region-file in which this block occurred with a previous version

The following attempts to fix it did not work:
- setblock air
- creative mode (crashes without breaking)

i would guess a external world editor like Amulet may also work.

**Comment by rubensworks** [comment]
Relevant part of the stacktrace:

```
java.lang.StackOverflowError: Unexpected error
	at java.util.Objects.hashCode(Objects.java:103) ~[?:?] {}
	at net.minecraft.resources.ResourceKey$InternKey.hashCode(ResourceKey.java:73) ~[client-1.20.1-20230612.114412-srg.jar%23156!/:?] {re:classloading}
	at com.google.common.base.Equivalence$Equals.doHash(Equivalence.java:392) ~[guava-31.1-jre.jar%2394!/:?] {}
	at com.google.common.base.Equivalence.hash(Equivalence.java:118) ~[guava-31.1-jre.jar%2394!/:?] {}
	at com.google.common.collect.MapMakerInternalMap.hash(MapMakerInternalMap.java:1078) ~[guava-31.1-jre.jar%2394!/:?] {}
	at com.google.common.collect.MapMakerInternalMap.get(MapMakerInternalMap.java:2341) ~[guava-31.1-jre.jar%2394!/:?] {}
	at java.util.concurrent.ConcurrentMap.computeIfAbsent(ConcurrentMap.java:329) ~[?:?] {}
	at net.minecraft.resources.ResourceKey.m_135790_(ResourceKey.java:30) ~[client-1.20.1-20230612.114412-srg.jar%23156!/:?] {re:classloading}
	at net.minecraft.resources.ResourceKey.m_135785_(ResourceKey.java:22) ~[client-1.20.1-20230612.114412-srg.jar%23156!/:?] {re:classloading}
	at net.minecraft.nbt.NbtUtils.m_247651_(NbtUtils.java:219) ~[client-1.20.1-20230612.114412-srg.jar%23156!/:?] {re:classloading}
	at org.cyclops.cyclopscore.helper.BlockHelpers.deserializeBlockState(BlockHelpers.java:83) ~[CyclopsCore-1.20.1-1.19.0.jar%23154!/:1.19.0] {re:classloading}
	at org.cyclops.integrateddynamics.capability.facadeable.FacadeableTileMultipartTicking.getFacade(FacadeableTileMultipartTicking.java:33) ~[IntegratedDynamics-1.20.1-1.21.1.jar%23155!/:1.21.1] {re:classloading}
	at org.cyclops.integrateddynamics.core.helper.CableHelpers.lambda$getFacade$5(CableHelpers.java:400) ~[IntegratedDynamics-1.20.1-1.21.1.jar%23155!/:1.21.1] {re:classloading}
	at java.util.Optional.flatMap(Optional.java:289) ~[?:?] {}
	at org.cyclops.integrateddynamics.core.helper.CableHelpers.getFacade(CableHelpers.java:400) ~[IntegratedDynamics-1.20.1-1.21.1.jar%23155!/:1.21.1] {re:classloading}
	at org.cyclops.integrateddynamics.block.BlockCable.m_7753_(BlockCable.java:382) ~[IntegratedDynamics-1.20.1-1.21.1.jar%23155!/:1.21.1] {re:classloading}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60739_(MixinBlockStateBase.java:551) ~[client-1.20.1-20230612.114412-srg.jar%23156!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.integrateddynamics.json:MixinBlockStateBase,pl:mixin:A}
	at org.cyclops.integrateddynamics.block.BlockCable.lambda$getLightBlock$2(BlockCable.java:383) ~[IntegratedDynamics-1.20.1-1.21.1.jar%23155!/:1.21.1] {re:classloading}
	at java.util.Optional.map(Optional.java:260) ~[?:?] {}
	at org.cyclops.integrateddynamics.block.BlockCable.m_7753_(BlockCable.java:383) 
```
