### ISSUE TITLE
Integrated Dynamics Item Rendering crashing in EMI view

### ISSUE THREAD

**Issue by rubensworks** [CyclopsMC/IntegratedDynamics#1366]
#### Issue type:

- :bug: Bug 

____

#### Short description:

```
[00:54:38] [Render thread/ERROR] [ne.ne.bu.EventBus/EVENTBUS]: Exception caught during firing event: Cannot invoke "net.minecraft.server.MinecraftServer.registryAccess()" because the return value of "net.neoforged.neoforge.server.ServerLifecycleHooks.getCurrentServer()" is null
    Index: 2
    Listeners:
        0: net.neoforged.bus.EventListenerFactory$eventContainerScreenEvent/0x00000287873a1400@40725ef5
        1: net.neoforged.bus.EventListenerFactory$drawMouseOver/0x0000028787a24400@43303d97
        2: dev.emi.emi.platform.neoforge.EmiClientNeoForge$$Lambda/0x000002878934af28@4c6898ba
        3: mezz.jei.core.util.WeakConsumer@65c57aa
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.MinecraftServer.registryAccess()" because the return value of "net.neoforged.neoforge.server.ServerLifecycleHooks.getCurrentServer()" is null
    at TRANSFORMER/integrateddynamics@1.21.5/org.cyclops.integrateddynamics.api.evaluate.variable.ValueDeseralizationContext.of(ValueDeseralizationContext.java:18)
    at TRANSFORMER/integrateddynamics@1.21.5/org.cyclops.integrateddynamics.core.client.model.VariableModelBaked$1.resolve(VariableModelBaked.java:96)
    at TRANSFORMER/minecraft@1.21/net.minecraft.client.renderer.entity.ItemRenderer.getModel(ItemRenderer.java:224)
    at TRANSFORMER/emi@1.1.10+1.21+neoforge/dev.emi.emi.api.stack.ItemEmiStack.isUnbatchable(ItemEmiStack.java:135)
```

#### Expected behaviour:

____

#### Versions:

- This mod: See version on Forgecraft
- Minecraft: 1.21
- Forge:

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by djnifos** [comment]
Looks like another case of this same getCurrentServer problem which looks to be without a failsafe https://github.com/CyclopsMC/IntegratedDynamics/blob/d3eb2579ead5d4f2898e00ed1a50e43e33eb5e94/src/main/java/org/cyclops/integrateddynamics/api/evaluate/variable/ValueDeseralizationContext.java#L18

https://mclo.gs/cBcLb16

<blockquote><img src="img/favicon.ico" width="48" align="right"><div>mclo.gs</div><div><strong><a href="https://mclo.gs/cBcLb16">NeoForge 1.21 Crash Report [#cBcLb16]</a></strong></div><div>407 lines</div></blockquote>

**Comment by micrwvae** [comment]
got some more logs that might help
https://github.com/AllTheMods/ATM-10/issues/137
