### ISSUE TITLE
op_by_name crashes server

### ISSUE THREAD

**Issue by kirjorjos** [CyclopsMC/IntegratedDynamics#1381]
#### Issue type:

- :bug: Bug 

____

#### Short description:
Using the op_by_name operator caused a server crash, after reboot, display panel behaves inconsistently (as shown in [1378](https://github.com/CyclopsMC/IntegratedDynamics/issues/1378)) even if card is taken out and put back in.  In order to cause a 2nd crash, network must be updated by placing any network part on it or destroying any part of the network.

#### Steps to reproduce the problem:

1. Get "Concat" as a string card
2. Put it in the op_by_name "tab" in the LP
3. Put the result in a display panel and "Concat" anywhere in the network

#### Expected behaviour:

If op_by_name isn't expecting that particular string, it should just display an X in the display panel.
____

#### Versions:

- This mod: Cyclops Core: 1.19.5
- CommonCapabilities: 2.9.2
- IntegratedDynamics: 1.23.0
- Minecraft: 1.19.2
- Forge: Client: 43.3.5
Server: 43.4.2

#### Log file: 
[crash-2024-08-14_06.18.56-server.txt](https://github.com/user-attachments/files/16607559/crash-2024-08-14_06.18.56-server.txt)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Note to self:
```
java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceLocation.toString()" because "uniqueName" is null
	at org.cyclops.integrateddynamics.core.evaluate.operator.OperatorRegistry.getOperator(OperatorRegistry.java:112) ~[IntegratedDynamics-1.19.2-1.23.0.jar%23116!/:1.23.0] {re:classloading}
	at org.cyclops.integrateddynamics.core.evaluate.operator.Operators.lambda$static$197(Operators.java:2942) ~[IntegratedDynamics-1.19.2-1.23.0.jar%23116!/:1.23.0] {re:classloading}
	at org.cyclops.integrateddynamics.core.evaluate.operator.OperatorBase.evaluate(OperatorBase.java:214) ~[IntegratedDynamics-1.19.2-1.23.0.jar%23116!/:1.23.0] {re:classloading}
```
