### ISSUE TITLE
Crash after start server

### ISSUE THREAD

**Issue by mkrtes** [CyclopsMC/IntegratedDynamics#162]
Full crashlog attached
// Ooh. Shiny.

Time: 19/03/17 13:41
Description: Exception in server tick loop

java.lang.IllegalStateException: The part container at north could not be found.
	at org.cyclops.integrateddynamics.core.network.PartNetworkElement.getPartState(PartNetworkElement.java:84)
	at org.cyclops.integrateddynamics.core.network.PartNetworkElement.getUpdateInterval(PartNetworkElement.java:100)
	at org.cyclops.integrateddynamics.core.network.Network.update(Network.java:374)
	at org.cyclops.integrateddynamics.core.TickHandler.onTick(TickHandler.java:54)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_348_TickHandler_onTick_TickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:635)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:591)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:261)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)
[crash-2017-03-19_13.41.51-server.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/853183/crash-2017-03-19_13.41.51-server.txt)

**Comment by rubensworks** [comment]
Please try the latest version `0.6.10` and let me know if it works, because that should've fixed this issue.
