### ISSUE TITLE
Right Clicking on Drying Basin in GM 3

### ISSUE THREAD

**Issue by ThomasAunvik** [CyclopsMC/IntegratedDynamics#164]
Right clicking on a drying basin in gamemode 3 kicks you out of the server with this error:
![img](http://i.imgur.com/joWAv5Y.png)

**Comment by rubensworks** [comment]
I see, never tested this myself before.

Note to self, I get this error when trying it in SSP:
```
Caused by: java.lang.NullPointerException
	at net.minecraft.inventory.InventoryBasic.<init>(InventoryBasic.java:33) ~[InventoryBasic.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.handleOpenWindow(NetHandlerPlayClient.java:1154) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.SPacketOpenWindow.processPacket(SPacketOpenWindow.java:47) ~[SPacketOpenWindow.class:?]
	at net.minecraft.network.play.server.SPacketOpenWindow.processPacket(SPacketOpenWindow.java:11) ~[SPacketOpenWindow.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0]
	at net.minecraft.util.Util.runTask(Util.java:25) ~[Util.class:?]
```
