### ISSUE TITLE
SF3 server crash on update from 3.0.8 to 3.0.9

### ISSUE THREAD

**Issue by broeredaan** [CyclopsMC/IntegratedDynamics#176]
Hey I'm having a crash after my server has started every time.

Crashlog says this:
java.lang.IllegalStateException: The part container at west could not be found.
	at org.cyclops.integrateddynamics.core.network.PartNetworkElement.getPartState(PartNetworkElement.java:92)
	at org.cyclops.integrateddynamics.core.network.PartNetworkElement.getUpdateInterval(PartNetworkElement.java:108)
	at org.cyclops.integrateddynamics.core.network.Network.update(Network.java:368)
	at org.cyclops.integrateddynamics.core.TickHandler.onTick(TickHandler.java:54)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_374_TickHandler_onTick_TickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:635)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:591)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:261)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

Any idea what I can do to fix this.

Running: 
FTBserver-1.10.2-12.18.3.2281
spongeforge-1.10.2-2281-5.2.0-BETA-2317
SkyFactory 3.0.9 (3.0.8 was fine)

Thanks.

**Comment by broeredaan** [comment]
Seems that removing sponge and after re-adding it solved my problem.

**Comment by rubensworks** [comment]
That's strange. World corruption would seem like the only possible cause of this.
A good thing you managed to fix it.
