### ISSUE TITLE
Mod doesn't work at all with ./gradlew runClient

### ISSUE THREAD

**Issue by josephcsible** [CyclopsMC/IntegratedDynamics#217]
I was doing some development on this mod and went to test my changes. I tried running the client from Eclipse and directly with `./gradlew runClient`, and the mod doesn't work at all either way. Here's the log:
https://gist.github.com/josephcsible/c0903c626da7421f4ca5992b8b5090bc

Important snippets:
This message repeated 22 times during startup:
```
[21:10:18] [main/WARN] [FML]: ****************************************
[21:10:18] [main/WARN] [FML]: * The API integrateddynamics|api from source {REDACTED}/IntegratedDynamics/build/libs/IntegratedDynamics-1.12-0.8.1-DEV.jar is loaded from an incompatible classloader. THIS WILL NOT WORK!
[21:10:18] [main/WARN] [FML]: *  at net.minecraftforge.fml.common.ModAPIManager$APIContainer.validate(ModAPIManager.java:114)
[21:10:18] [main/WARN] [FML]: *  at net.minecraftforge.fml.common.ModAPIManager.registerDataTableAndParseAPI(ModAPIManager.java:174)
[21:10:18] [main/WARN] [FML]: *  at net.minecraftforge.fml.common.ModAPIManager.manageAPI(ModAPIManager.java:232)
[21:10:18] [main/WARN] [FML]: *  at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:544)
[21:10:18] [main/WARN] [FML]: *  at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:227)
[21:10:18] [main/WARN] [FML]: *  at net.minecraft.client.Minecraft.init(Minecraft.java:508)...
[21:10:18] [main/WARN] [FML]: ****************************************
```
Although once, one of the lines was changed to this:
```
[21:10:18] [main/WARN] [FML]: * The API commoncapabilities|api from source {REDACTED}/.gradle/caches/minecraft/deobfedDeps/deobf/org/cyclops/commoncapabilities/CommonCapabilities/1.12-1.3.3-125/CommonCapabilities-1.12-1.3.3-125.jar is loaded from an incompatible classloader. THIS WILL NOT WORK!
```
When I tried to open a GUI, I got this exception and the GUI didn't open:
```
[21:10:35] [main/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Invalid GUI data.
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_131]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_131]
        at net.minecraft.util.Util.runTask(Util.java:54) [Util.class:?]
        at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1161) [Minecraft.class:?]
        at net.minecraft.client.Minecraft.run(Minecraft.java:436) [Minecraft.class:?]
        at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
        at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.IllegalArgumentException: Invalid GUI data.
        at org.cyclops.cyclopscore.client.gui.GuiHandler.getTemporaryData(GuiHandler.java:86) ~[GuiHandler.class:?]
        at org.cyclops.cyclopscore.client.gui.GuiHandler.getClientGuiElement(GuiHandler.java:110) ~[GuiHandler.class:?]
        at net.minecraftforge.fml.common.network.NetworkRegistry.getLocalGuiContainer(NetworkRegistry.java:277) ~[NetworkRegistry.class:?]
        atnecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:110) ~[FMLNetworkHandler.class:?]
        at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2776) ~[EntityPlayer.class:?]
        at net.minecraftforge.fml.common.network.internal.OpenGuiHandler.process(OpenGuiHandler.java:50) ~[OpenGuiHandler.class:?]
        at net.minecraftforge.fml.common.network.internal.OpenGuiHandler.lambda$channelRead0$0(OpenGuiHandler.java:43) ~[OpenGuiHandler.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_131]
        at net.minecraft.util.Util.runTask(Util.java:53) ~[Util.class:?]
        ... 15 more
```

When I run `./gradlew build` and try the resulting jar file in a regular Minecraft instance, it works fine.

**Comment by rubensworks** [comment]
Hmm, this might have something to do with some recent `MinecraftHelpers#isClientSide()` changes in CyclopsCore. Could you try manually updating CyclopsCore in your `build.properties` to version `1.11.2-0.10.6-580` (the latest)?

**Comment by josephcsible** [comment]
`0.10.6-580` is for 1.11.2, but I'm on 1.12. I instead changed it to `0.10.9-614` and that does indeed fix the GUI, but I still get all of the scary incompatible classloader messages.

**Comment by rubensworks** [comment]
You can ignore the classloader messages, that just because the API package is include in a dev environment, which is normal because it is included here as a source package. This message is not present when the mod is built.

Feel free to send a PR for the CC version number fix. (And close this issue if your problem is resolved :-) )
