### ISSUE TITLE
Crash when using /setblock

### ISSUE THREAD

**Issue by josephcsible** [CyclopsMC/IntegratedDynamics#240]
With this setup (variable card from the redstone reader in the display screen), using /setblock to change the block with the redstone reader to air causes the game to crash:
![2017-08-13_00 05 22](https://user-images.githubusercontent.com/16061266/29246068-74f2293c-7fbb-11e7-8847-1730f609e967.png)
This happened with Minecraft 1.12.1, Forge 14.22.0.2452, CyclopsCore 0.10.12, CommonCapabilities 1.3.4, IntegratedDynamics 0.8.4, and no other mods. Here's what the log says:
```
[00:05:44] [Server thread/INFO]: [josephcsible: Block placed]
[00:05:44] [main/INFO]: [CHAT] Block placed
[00:05:44] [Server thread/WARN]: Attempted to tick a part that was not properly unloaded. Report this to the Integrated Dynamics issue tracker with details on what you did leading up to this stacktrace. The part was forcefully unloaded
[00:05:44] [Server thread/INFO]: [org.cyclops.integrateddynamics.core.network.Network:update:398]: org.cyclops.integrateddynamics.api.PartStateException: No part state for part at position DimPos(dimensionId=0, blockPos=BlockPos{x=529, y=4, z=-155}, worldReference=null) side east was found.
World loaded: true
Chunk loaded: true
Part container: null
Parts: null
[00:05:44] [Server thread/INFO]: [org.cyclops.integrateddynamics.core.network.Network:update:398]: 	at org.cyclops.integrateddynamics.core.network.PartNetworkElement.getPartState(PartNetworkElement.java:96)
[00:05:44] [Server thread/INFO]: [org.cyclops.integrateddynamics.core.network.Network:update:398]: 	at org.cyclops.integrateddynamics.core.network.PartNetworkElement.getUpdateInterval(PartNetworkElement.java:112)
[00:05:44] [Server thread/INFO]: [org.cyclops.integrateddynamics.core.network.Network:update:398]: 	at org.cyclops.integrateddynamics.core.network.Network.update(Network.java:375)
[00:05:44] [Server thread/INFO]: [org.cyclops.integrateddynamics.core.network.Network:update:398]: 	at org.cyclops.integrateddynamics.core.TickHandler.onTick(TickHandler.java:54)
[00:05:44] [Server thread/INFO]: [org.cyclops.integrateddynamics.core.network.Network:update:398]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_42_TickHandler_onTick_TickEvent.invoke(.dynamic)
[00:05:44] [Server thread/INFO]: [org.cyclops.integrateddynamics.core.network.Network:update:398]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[00:05:44] [Server thread/INFO]: [org.cyclops.integrateddynamics.core.network.Network:update:398]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
[00:05:44] [Server thread/INFO]: [org.cyclops.integrateddynamics.core.network.Network:update:398]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:264)
[00:05:44] [Server thread/INFO]: [org.cyclops.integrateddynamics.core.network.Network:update:398]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:710)
[00:05:44] [Server thread/INFO]: [org.cyclops.integrateddynamics.core.network.Network:update:398]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
[00:05:44] [Server thread/INFO]: [org.cyclops.integrateddynamics.core.network.Network:update:398]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
[00:05:44] [Server thread/INFO]: [org.cyclops.integrateddynamics.core.network.Network:update:398]: 	at java.lang.Thread.run(Thread.java:745)
[00:05:45] [Server thread/ERROR]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$ServerTickEvent@4df6b158:
java.lang.NullPointerException: null
	at org.cyclops.integrateddynamics.core.network.NetworkElementBase.revalidatePositioned(NetworkElementBase.java:97) ~[NetworkElementBase.class:?]
	at org.cyclops.integrateddynamics.core.network.PartNetworkElement.revalidate(PartNetworkElement.java:74) ~[PartNetworkElement.class:?]
	at org.cyclops.integrateddynamics.core.network.Network.isValid(Network.java:531) ~[Network.class:?]
	at org.cyclops.integrateddynamics.core.network.Network.update(Network.java:367) ~[Network.class:?]
	at org.cyclops.integrateddynamics.core.TickHandler.onTick(TickHandler.java:54) ~[TickHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_42_TickHandler_onTick_TickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:264) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:710) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
[00:05:45] [Server thread/ERROR]: Index: 1 Listeners:
[00:05:45] [Server thread/ERROR]: 0: NORMAL
[00:05:45] [Server thread/ERROR]: 1: ASM: org.cyclops.integrateddynamics.core.TickHandler@2de0f3e3 onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[00:05:45] [Server thread/ERROR]: 2: ASM: org.cyclops.integrateddynamics.core.NoteBlockEventReceiver@212d8133 onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[00:05:45] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException: null
	at org.cyclops.integrateddynamics.core.network.NetworkElementBase.revalidatePositioned(NetworkElementBase.java:97) ~[NetworkElementBase.class:?]
	at org.cyclops.integrateddynamics.core.network.PartNetworkElement.revalidate(PartNetworkElement.java:74) ~[PartNetworkElement.class:?]
	at org.cyclops.integrateddynamics.core.network.Network.isValid(Network.java:531) ~[Network.class:?]
	at org.cyclops.integrateddynamics.core.network.Network.update(Network.java:367) ~[Network.class:?]
	at org.cyclops.integrateddynamics.core.TickHandler.onTick(TickHandler.java:54) ~[TickHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_42_TickHandler_onTick_TickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:264) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:710) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
```

**Comment by josephcsible** [comment]
This looks like it might actually have the same cause as #232.
