### ISSUE TITLE
Crash when Energy Battery is ticking

### ISSUE THREAD

**Issue by squirrelkiller** [CyclopsMC/IntegratedDynamics#38]
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
  IC2core (industrialcraft-2-2.3.232-ex18.jar)
  FMLPlugin (InventoryTweaks-1.60-40.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 09/05/16 2:56 PM
Description: Ticking block entity

java.lang.IllegalArgumentException: Cannot set property PropertyInteger{name=fill, clazz=class java.lang.Integer, values=[0, 1, 2, 3]} as it does not exist in BlockState{block=minecraft:bedrock, properties=[]}
    at net.minecraft.block.state.BlockState$StateImplementation.func_177226_a(BlockState.java:156)
    at org.cyclops.integrateddynamics.tileentity.TileEnergyBattery.updateBlockState(TileEnergyBattery.java:54)
    at org.cyclops.integrateddynamics.tileentity.TileEnergyBattery.setEnergy(TileEnergyBattery.java:61)
    at org.cyclops.integrateddynamics.tileentity.TileEnergyBattery.addEnergy(TileEnergyBattery.java:72)
    at org.cyclops.integrateddynamics.core.network.PartNetwork.addEnergy(PartNetwork.java:347)
    at org.cyclops.integrateddynamics.tileentity.TileCoalGenerator.addEnergy(TileCoalGenerator.java:70)
    at org.cyclops.integrateddynamics.tileentity.TileCoalGenerator.updateTileEntity(TileCoalGenerator.java:89)
    at org.cyclops.cyclopscore.tileentity.CyclopsTileEntity.updateTicking(CyclopsTileEntity.java:94)
    at org.cyclops.cyclopscore.tileentity.CyclopsTileEntity.access$000(CyclopsTileEntity.java:37)
    at org.cyclops.cyclopscore.tileentity.CyclopsTileEntity$TickingTileComponent.func_73660_a(CyclopsTileEntity.java:322)
    at org.cyclops.integrateddynamics.core.tileentity.TileCableConnectableInventory.func_73660_a(TileCableConnectableInventory.java:18)
    at net.minecraft.world.World.func_72939_s(World.java:1718)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at net.minecraft.block.state.BlockState$StateImplementation.func_177226_a(BlockState.java:156)
    at org.cyclops.integrateddynamics.tileentity.TileEnergyBattery.updateBlockState(TileEnergyBattery.java:54)
    at org.cyclops.integrateddynamics.tileentity.TileEnergyBattery.setEnergy(TileEnergyBattery.java:61)
    at org.cyclops.integrateddynamics.tileentity.TileEnergyBattery.addEnergy(TileEnergyBattery.java:72)
    at org.cyclops.integrateddynamics.core.network.PartNetwork.addEnergy(PartNetwork.java:347)
    at org.cyclops.integrateddynamics.tileentity.TileCoalGenerator.addEnergy(TileCoalGenerator.java:70)
    at org.cyclops.integrateddynamics.tileentity.TileCoalGenerator.updateTileEntity(TileCoalGenerator.java:89)
    at org.cyclops.cyclopscore.tileentity.CyclopsTileEntity.updateTicking(CyclopsTileEntity.java:94)
    at org.cyclops.cyclopscore.tileentity.CyclopsTileEntity.access$000(CyclopsTileEntity.java:37)
    at org.cyclops.cyclopscore.tileentity.CyclopsTileEntity$TickingTileComponent.func_73660_a(CyclopsTileEntity.java:322)
    at org.cyclops.integrateddynamics.core.tileentity.TileCableConnectableInventory.func_73660_a(TileCableConnectableInventory.java:18)

-- Block entity being ticked --
Details:
    Name: coalGenerator // org.cyclops.integrateddynamics.tileentity.TileCoalGenerator
    Block type: ID #303 (tile.blocks.integrateddynamics.coalGenerator // org.cyclops.integrateddynamics.block.BlockCoalGenerator)
    Block data value: 5 / 0x5 / 0b0101
    Block location: World: (-123,67,217), Chunk: (at 5,4,9 in -8,13; contains blocks -128,0,208 to -113,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Actual block type: ID #303 (tile.blocks.integrateddynamics.coalGenerator // org.cyclops.integrateddynamics.block.BlockCoalGenerator)
    Actual block data value: 5 / 0x5 / 0b0101
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1718)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545)

-- Affected level --
Details:
    Level name: New World
    All players: 1 total; [EntityPlayerMP['squirrel_killer'/573, l='New World', x=-120.12, y=67.00, z=216.84]]
    Chunk stats: ServerChunkCache: 289 Drop: 0
    Level seed: -8514946196675323612
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: -112.00,64.00,256.00 - World: (-112,64,256), Chunk: (at 0,4,0 in -7,16; contains blocks -112,0,256 to -97,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 84699 game time, 975 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1630792624 bytes (1555 MB) / 2423783424 bytes (2311 MB) up to 4131389440 bytes (3940 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4431m -Xms256m -XX:PermSize=256m
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP 9.19 Powered by Forge 11.15.1.1890 31 mods loaded, 31 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1890-1.8.9.jar) 
    UCHIJAAAA   Forge{11.15.1.1890} [Minecraft Forge] (forge-1.8.9-11.15.1.1890-1.8.9.jar) 
    UCHIJAAAA   Chameleon{1.8.9-1.1.2} [Chameleon] (Chameleon-1.8.9-1.1.2.jar) 
    UCHIJAAAA   mcmultipart{1.0.9} [MCMultiPart] (MCMultiPart-1.0.9-universal.jar) 
    UCHIJAAAA   CharsetLib{0.2.5} [â€½] (Charset-0.2.5-a5313e6797c07288da5559c1.jar) 
    UCHIJAAAA   CharsetPipes{0.2.5} [|] (Charset-0.2.5-a5313e6797c07288da5559c1.jar) 
    UCHIJAAAA   CharsetWires{0.2.5} [+] (Charset-0.2.5-a5313e6797c07288da5559c1.jar) 
    UCHIJAAAA   CharsetAudio{0.2.5} [â™«] (Charset-0.2.5-a5313e6797c07288da5559c1.jar) 
    UCHIJAAAA   CharsetDrama{0.2.5} [!] (Charset-0.2.5-a5313e6797c07288da5559c1.jar) 
    UCHIJAAAA   CharsetStorage{0.2.5} [#] (Charset-0.2.5-a5313e6797c07288da5559c1.jar) 
    UCHIJAAAA   CharsetTweaks{0.2.5} [*] (Charset-0.2.5-a5313e6797c07288da5559c1.jar) 
    UCHIJAAAA   CharsetGates{0.2.5} [&] (Charset-0.2.5-a5313e6797c07288da5559c1.jar) 
    UCHIJAAAA   chiselsandbits{8.8} [Chisels & Bits] (chiselsandbits-8.8.jar) 
    UCHIJAAAA   cyclopscore{0.5.6} [Cyclops Core] (CyclopsCore-1.8.9-0.5.6.jar) 
    UCHIJAAAA   evilcraft{0.9.7} [EvilCraft] (EvilCraft-1.8.9-0.9.7.jar) 
    UCHIJAAAA   IC2{2.3.232-ex18} [IndustrialCraft 2] (industrialcraft-2-2.3.232-ex18.jar) 
    UCHIJAAAA   integrateddynamics{0.3.8} [Integrated Dynamics] (IntegratedDynamics-1.8.9-0.3.8.jar) 
    UCHIJAAAA   inventorytweaks{1.60-40-e06e29a} [Inventory Tweaks] (InventoryTweaks-1.60-40.jar) 
    UCHIJAAAA   IronChest{6.0.125.770} [Iron Chest] (ironchest-1.8.9-6.0.125.770.jar) 
    UCHIJAAAA   JEI{2.28.18.186} [Just Enough Items] (jei_1.8.9-2.28.18.186.jar) 
    UCHIJAAAA   Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
    UCHIJAAAA   Thaumcraft{5.2.4} [Thaumcraft] (Thaumcraft-1.8.9-5.2.4.jar) 
    UCHIJAAAA   JEIAddons{0.12.0.57} [Just Enough Items Addons] (JEIAddons_1.8.9-0.12.0.57.jar) 
    UCHIJAAAA   journeymap{1.8.9-5.2.0b1} [JourneyMap] (journeymap-1.8.9-5.2.0b1-unlimited.jar) 
    UCHIJAAAA   jeresources{0.4.0} [Just Enough Resources] (JustEnoughResources-1.8.9-0.4.0.23.jar) 
    UCHIJAAAA   RecipeTooltips{1.1.24} [RecipeTooltips] (RecipeTooltips-1.8.9-1.1.24.jar) 
    UCHIJAAAA   StorageDrawers{1.8.9-2.6.4} [Storage Drawers] (StorageDrawers-1.8.9-2.6.4.jar) 
    UCHIJAAAA   Waila{1.6.0} [Waila] (Waila-1.6.0-B3_1.8.8.jar) 
    UCHIJAAAA   WailaHarvestability{1.1.7} [Waila Harvestability] (WailaHarvestability-mc1.8.x-1.1.7.jar) 
    UCHIJAAAA   wawla{1.1.4.168} [What Are We Looking At] (Wawla-1.8.9-1.1.4.171.jar) 
    Loaded coremods (and transformers): 
ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)

IC2core (industrialcraft-2-2.3.232-ex18.jar)

FMLPlugin (InventoryTweaks-1.60-40.jar)
  invtweaks.forge.asm.ContainerTransformer
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    Profiler Position: N/A (disabled)
    Player Count: 1 / 8; [EntityPlayerMP['squirrel_killer'/573, l='New World', x=-120.12, y=67.00, z=216.84]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'
```

Placed coal in generator beside battery block, RF was not enabled, it was for demo reasons.

**Comment by squirrelkiller** [comment]
Additional information: A minor issue, I can't break the blocks even in creative they stay there now.
