### ISSUE TITLE
Crash when breaking cabling in creative

### ISSUE THREAD

**Issue by squirrelkiller** [CyclopsMC/IntegratedDynamics#39]
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
  IC2core (industrialcraft-2-2.3.232-ex18.jar)
  FMLPlugin (InventoryTweaks-1.60-40.jar)
Contact their authors BEFORE contacting forge

// Oh - I know what I did wrong!

Time: 10/05/16 9:11 PM
Description: Exception in server tick loop

java.lang.IllegalArgumentException: No part at position DimPos(world=net.minecraft.world.WorldServer@2cf08366, blockPos=BlockPos{x=168, y=4, z=1056}) was found to get the state from.
    at org.cyclops.integrateddynamics.core.tileentity.TileMultipartTicking.getPartState(TileMultipartTicking.java:210)
    at org.cyclops.integrateddynamics.core.network.PartNetworkElement.getPartState(PartNetworkElement.java:56)
    at org.cyclops.integrateddynamics.core.network.PartNetworkElement.beforeNetworkKill(PartNetworkElement.java:92)
    at org.cyclops.integrateddynamics.core.network.PartNetworkElement.beforeNetworkKill(PartNetworkElement.java:22)
    at org.cyclops.integrateddynamics.core.network.Network.kill(Network.java:224)
    at org.cyclops.integrateddynamics.core.network.Network.killIfEmpty(Network.java:232)
    at org.cyclops.integrateddynamics.core.network.Network.update(Network.java:257)
    at org.cyclops.integrateddynamics.core.TickHandler.onTick(TickHandler.java:32)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_88_TickHandler_onTick_TickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:253)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:649)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1727576480 bytes (1647 MB) / 2388131840 bytes (2277 MB) up to 4131389440 bytes (3940 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4431m -Xms256m -XX:PermSize=256m
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.19 Powered by Forge 11.15.1.1890 31 mods loaded, 31 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1890-1.8.9.jar) 
    UCHIJAAAA   Forge{11.15.1.1890} [Minecraft Forge] (forge-1.8.9-11.15.1.1890-1.8.9.jar) 
    UCHIJAAAA   Chameleon{1.8.9-1.1.2} [Chameleon] (Chameleon-1.8.9-1.1.2.jar) 
    UCHIJAAAA   mcmultipart{1.0.9} [MCMultiPart] (MCMultiPart-1.0.9-universal.jar) 
    UCHIJAAAA   CharsetLib{0.2.5} [â€½] (Charset-0.2.5-a5313e6797c07288da5559c1.jar) 
    UCHIJAAAA   CharsetPipes{0.2.5} [|] (Charset-0.2.5-a5313e6797c07288da5559c1.jar) 
    UCHIJAAAA   CharsetWires{0.2.5} [+] (Charset-0.2.5-a5313e6797c07288da5559c1.jar) 
    UCHIJAAAA   CharsetAudio{0.2.5} [â™«] (Charset-0.2.5-a5313e6797c07288da5559c1.jar) 
    UCHIJAAAA   CharsetDrama{0.2.5} [!] (Charset-0.2.5-a5313e6797c07288da5559c1.jar) 
    UCHIJAAAA   CharsetStorage{0.2.5} [#] (Charset-0.2.5-a5313e6797c07288da5559c1.jar) 
    UCHIJAAAA   CharsetTweaks{0.2.5} [*] (Charset-0.2.5-a5313e6797c07288da5559c1.jar) 
    UCHIJAAAA   CharsetGates{0.2.5} [&] (Charset-0.2.5-a5313e6797c07288da5559c1.jar) 
    UCHIJAAAA   chiselsandbits{8.8} [Chisels & Bits] (chiselsandbits-8.8.jar) 
    UCHIJAAAA   cyclopscore{0.5.6} [Cyclops Core] (CyclopsCore-1.8.9-0.5.6.jar) 
    UCHIJAAAA   evilcraft{0.9.7} [EvilCraft] (EvilCraft-1.8.9-0.9.7.jar) 
    UCHIJAAAA   IC2{2.3.232-ex18} [IndustrialCraft 2] (industrialcraft-2-2.3.232-ex18.jar) 
    UCHIJAAAA   integrateddynamics{0.3.8} [Integrated Dynamics] (IntegratedDynamics-1.8.9-0.3.8.jar) 
    UCHIJAAAA   inventorytweaks{1.60-40-e06e29a} [Inventory Tweaks] (InventoryTweaks-1.60-40.jar) 
    UCHIJAAAA   IronChest{6.0.125.770} [Iron Chest] (ironchest-1.8.9-6.0.125.770.jar) 
    UCHIJAAAA   JEI{2.28.18.186} [Just Enough Items] (jei_1.8.9-2.28.18.186.jar) 
    UCHIJAAAA   Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
    UCHIJAAAA   Thaumcraft{5.2.4} [Thaumcraft] (Thaumcraft-1.8.9-5.2.4.jar) 
    UCHIJAAAA   JEIAddons{0.12.0.57} [Just Enough Items Addons] (JEIAddons_1.8.9-0.12.0.57.jar) 
    UCHIJAAAA   journeymap{1.8.9-5.2.0b1} [JourneyMap] (journeymap-1.8.9-5.2.0b1-unlimited.jar) 
    UCHIJAAAA   jeresources{0.4.0} [Just Enough Resources] (JustEnoughResources-1.8.9-0.4.0.23.jar) 
    UCHIJAAAA   RecipeTooltips{1.1.24} [RecipeTooltips] (RecipeTooltips-1.8.9-1.1.24.jar) 
    UCHIJAAAA   StorageDrawers{1.8.9-2.6.4} [Storage Drawers] (StorageDrawers-1.8.9-2.6.4.jar) 
    UCHIJAAAA   Waila{1.6.0} [Waila] (Waila-1.6.0-B3_1.8.8.jar) 
    UCHIJAAAA   WailaHarvestability{1.1.7} [Waila Harvestability] (WailaHarvestability-mc1.8.x-1.1.7.jar) 
    UCHIJAAAA   wawla{1.1.4.168} [What Are We Looking At] (Wawla-1.8.9-1.1.4.171.jar) 
    Loaded coremods (and transformers): 
ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)

IC2core (industrialcraft-2-2.3.232-ex18.jar)

FMLPlugin (InventoryTweaks-1.60-40.jar)
  invtweaks.forge.asm.ContainerTransformer
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    Profiler Position: N/A (disabled)
    Player Count: 1 / 8; [EntityPlayerMP['squirrel_killer'/290, l='Tutorial', x=165.18, y=4.00, z=1057.30]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by rubensworks** [comment]
@squirrelkiller Could you explain in detail the steps that are required in order to reproduce this crash?

**Comment by squirrelkiller** [comment]
Step 1, build quite massive network (about 30+ devices I think by that point).
Step 2, have them all moving information around between each other.
Step 3, Smash several blocks drawing information from other parts of the network, starting with the cable each time. I believe I specifically hit the cable connecting to an audio writer which was reading from inventory reader about a chunk and a half away. I hit the cable, then the writer.
Step 4, Be confused because I had smashed several other devices before the crash.

I can tell you the network had literally every type of reader and writer functioning on it at the time. Tutorial videos can demand a lot from a mod, because you are showing everything at once.

**Comment by rubensworks** [comment]
I'm unable to reproduce this in the latest ID version (not yet released). I assume this is fixed for now.
