### ISSUE TITLE
crash diamond backpack in drying basin

### ISSUE THREAD

**Issue by mabelrxu** [CyclopsMC/IntegratedDynamics#414]
#### Issue type:

_Only keep the issue types that are applicable._

- :bug: Bug

____
#### Short description:
Crash when accidentally putting diamond backpack - storage focus (iron backpacks mod) into drying basin.

#### Expected behaviour:
No crash, no interaction, able to take backpack back out

#### Actual behaviour:
Crashed with error saying cannot support more than 32,000-ish items.

#### Steps to reproduce the problem:

1. Create diamond backpack, storage focus from iron backpacks.
2. (optional?) put various forestry backpacks inside the diamond backpack
3. accidentally put the diamond backpack into the drying basin
4. crash

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: 1.12.2-0.9.6
- CyclopsCore: 1.12.2-0.10.23
- Minecraft: 1.12.2
- Forge: 14.23.0.2531

#### Log file:

Not sure where to find crash report ... here's the relevant log entry:
[11:27:39] [Netty Local Client IO #1/ERROR]: NetworkDispatcher exception
java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes
	at net.minecraft.network.play.client.CPacketCustomPayload.<init>(CPacketCustomPayload.java:28) ~[lh.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.toC17Packet(FMLProxyPacket.java:142) ~[FMLProxyPacket.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.write(NetworkDispatcher.java:524) ~[NetworkDispatcher.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[DefaultChannelPipeline.class:4.1.9.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[AbstractChannel.class:4.1.9.Final]
	at net.minecraft.network.NetworkManager$4.run(NetworkManager.java:245) [gw$4.class:?]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) [DefaultEventLoop.class:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [SingleThreadEventExecutor$5.class:4.1.9.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
[11:27:39] [Netty Local Client IO #1/INFO]: [AstralSorcery] Cleaning client cache...
[11:27:39] [Netty Local Client IO #1/INFO]: [AstralSorcery] Cleared cached client data! Disconnected from server.

**Comment by mabelrxu** [comment]
Hm ... just crashed while doing something else after reloading an easier backup that didn't have a drying basin at all, maybe it's not from integrated dynamics

**Comment by rubensworks** [comment]
Nesting backpacks in backpacks in MC is never a good idea. Unfortunately, that's a vanilla restriction.
