### ISSUE TITLE
Tons of spam in console

### ISSUE THREAD

**Issue by fcpwiz** [CyclopsMC/IntegratedDynamics#588]
#### Issue type:

- :bug: Bug

____

#### Short description:

Tons of spam in the console, unable to stop it.

#### Steps to reproduce the problem:

1. ...

#### Expected behaviour:

No spam.
____

#### Versions:

- This mod: IntegratedDynamics-1.12.2-0.11.12.jar
- Minecraft: 1.12.2
- Forge: 2705

#### Log file:

https://gist.github.com/fcpwiz/b3e5f8381966dc0241457eaf167f08a2

**Comment by phantamanta44** [comment]
The networks in question were integrated tunnels networks transferring items between various mekanism and thermal expansion machines and some storage drawers. They seemed to function perfectly fine despite the console spam. All of the networks were contained within a single chunk.

**Comment by rubensworks** [comment]
That's strange, somehow the network part lost its reference to the network. Haven't seen that happening before.

**Comment by rubensworks** [comment]
Note to self: related to #283.

**Comment by rubensworks** [comment]
(Same as #283)

This issue has been open for a long time now. If this was in fact a Forge issue, it has been fixed (MinecraftForge/MinecraftForge#4413).

Should anyone else be encountering this issue, please let me know here. Closing this issue otherwise.

**Comment by Jakub-Wilk** [comment]
Hi, experiencing this in MC Eternal 2 right now. This:

```
Parts: null
[26Jul2025 18:14:46.967] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:651]: 	at TRANSFORMER/integrateddynamics@1.24.3/org.cyclops.integrateddynamics.core.helper.PartHelpers.lambda$getPartContainerChecked$1(PartHelpers.java:104)
[26Jul2025 18:14:46.967] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:651]: 	at TRANSFORMER/forge@47.4.2/net.minecraftforge.common.util.LazyOptional.orElseThrow(LazyOptional.java:261)
[26Jul2025 18:14:46.967] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:651]: 	at TRANSFORMER/integrateddynamics@1.24.3/org.cyclops.integrateddynamics.core.helper.PartHelpers.getPartContainerChecked(PartHelpers.java:104)
[26Jul2025 18:14:46.967] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:651]: 	at TRANSFORMER/integrateddynamics@1.24.3/org.cyclops.integrateddynamics.core.network.PartNetworkElement.getPartContainer(PartNetworkElement.java:88)
[26Jul2025 18:14:46.968] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:651]: 	at TRANSFORMER/integrateddynamics@1.24.3/org.cyclops.integrateddynamics.core.network.PartNetworkElement.getPartState(PartNetworkElement.java:138)
[26Jul2025 18:14:46.968] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:651]: 	at TRANSFORMER/integrateddynamics@1.24.3/org.cyclops.integrateddynamics.core.network.PartNetworkElement.getUpdateInterval(PartNetworkElement.java:158)
[26Jul2025 18:14:46.968] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:651]: 	at TRANSFORMER/integrateddynamics@1.24.3/org.cyclops.integrateddynamics.core.network.Network.update(Network.java:412)
[26Jul2025 18:14:46.968] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:651]: 	at TRANSFORMER/integrateddynamics@1.24.3/org.cyclops.integrateddynamics.core.TickHandler.onTick(TickHandler.java:74)
[26Jul2025 18:14:46.968] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:651]: 	at TRANSFORMER/integrateddynamics@1.24.3/org.cyclops.integrateddynamics.core.__TickHandler_onTick_TickEvent.invoke(.dynamic)
[26Jul2025 18:14:46.968] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:651]: 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
[26Jul2025 18:14:46.968] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:651]: 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
[26Jul2025 18:14:46.968] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:651]: 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
[26Jul2025 18:14:46.968] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:651]: 	at TRANSFORMER/forge@47.4.2/net.minecraftforge.event.ForgeEventFactory.onPostServerTick(ForgeEventFactory.java:975)
[26Jul2025 18:14:46.968] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:651]: 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:835)
[26Jul2025 18:14:46.968] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:651]: 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661)
[26Jul2025 18:14:46.968] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:651]: 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
[26Jul2025 18:14:46.968] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:651]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[26Jul2025 18:14:46.968] [Server thread/WARN] [integrateddynamics/]: Attempted to tick a part that was not properly unloaded. Report this to the Integrated Dynamics issue tracker with details on what you did leading up to this stacktrace. The part was forcefully unloaded
[26Jul2025 18:14:46.968] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:651]: org.cyclops.integrateddynamics.api.PartStateException: No part state for part at position DimPos(level=minecraft:overworld, blockPos=BlockPos{x=-4610, y=73, z=2835}, worldReference=null) side south
```
is being spammed at multiple locations (I counted at least 3 that are not close to each other). The error is thrown every 1-10ms, which leads to latest.log being 96 GB at the time of the latest server crash. I can't investigate what block is at those locations right now, but I'll provide that soon.

**Comment by rubensworks** [comment]
@Jakub-Wilk if you're using the latest ID version, can you open a new bug report?

**Comment by Jakub-Wilk** [comment]
Not at latest version, since we're running as part of a modpack. I'll try bumping the versions of all Integrated mods and report back if it happens again.
