### ISSUE TITLE
Crash during worldgen if filled menril log is disabled

### ISSUE THREAD

**Issue by VladoCC** [CyclopsMC/IntegratedDynamics#598]
#### Issue type:

- :bug: Bug

____

#### Short description:

Server just crashed with NullPointer

#### Steps to reproduce the problem:

Don't know.
Just go for a walf, maybe start to generate new chunks.

1. ...

#### Expected behaviour:

Nothing

____

#### Versions:

- This mod: 0.11. 13
- Minecraft: 1.12.2
- Forge: 14.23.4.2725

#### Log file:

[Full log](https://pastebin.com/d6zYW8wc)

For faster search, just stacktrace:

> Caused by: java.lang.NullPointerException
	at org.cyclops.integrateddynamics.world.gen.WorldGeneratorMenrilTree.growTree(WorldGeneratorMenrilTree.java:179) ~[WorldGeneratorMenrilTree.class:?]
	at org.cyclops.integrateddynamics.block.BlockMenrilSaplingConfig.onDecorate(BlockMenrilSaplingConfig.java:62) ~[BlockMenrilSaplingConfig.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_989_BlockMenrilSaplingConfig_onDecorate_Decorate.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.event.terraingen.TerrainGen.decorate(TerrainGen.java:88) ~[TerrainGen.class:?]
	at net.minecraft.world.biome.BiomeDecorator.func_150513_a(BiomeDecorator.java:130) ~[ank.class:?]
	at net.minecraft.world.biome.BiomeDecorator.func_180292_a(BiomeDecorator.java:88) ~[ank.class:?]
	at net.minecraft.world.biome.Biome.func_180624_a(Biome.java:225) ~[anh.class:?]
	at net.minecraft.world.biome.BiomeForest.func_180624_a(BiomeForest.java:110) ~[anr.class:?]
	at net.minecraft.world.gen.ChunkGeneratorOverworld.func_185931_b(ChunkGeneratorOverworld.java:464) ~[aze.class:?]
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1017) ~[axw.class:?]
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:983) ~[axw.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157) ~[on.class:?]
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126) ~[ot.class:?]
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147) ~[ou.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756) ~[MinecraftServer.class:?]
	... 4 more

**Comment by VladoCC** [comment]
I'd checked code which caused an exception and maybe I know what went wrong.
I'd disabled menril_log_filled in config. I thnik that for this reasone when your code want to place illed wood it crashes

**Comment by rubensworks** [comment]
Indeed, that makes sense. I should add a safety check in the worldgen code to not generated filled menril logs if they are disabled.

**Comment by VladoCC** [comment]
Please, fix it ASAP, because I crashed already 3 times.

**Comment by VladoCC** [comment]
I aalready fixed it myself and created pull request.

**Comment by rubensworks** [comment]
See #600

**Comment by VladoCC** [comment]
And of course, this checks is need to be added to every block in your mod, which generates in the world
