### ISSUE TITLE
Proxy crash

### ISSUE THREAD

**Issue by TheBigBadWolf2** [CyclopsMC/IntegratedDynamics#691]
When I opened up the proxy after removing some of the variables the card in it references, the game crashed

#### Versions:

- This mod: 1.12.2-1.0.4
- Minecraft: 1.12.2
- Forge: 14.23.5.2808

#### Log file:
I tried uploading the log to pastebin but is said it was too big, but here is the zip file:
[2019-02-09-2.log.gz](https://github.com/CyclopsMC/IntegratedDynamics/files/2848351/2019-02-09-2.log.gz)

**Comment by rubensworks** [comment]
Note to self:

```
org.cyclops.integrateddynamics.api.PartStateException: No part state for part at position DimPos(dimensionId=0, blockPos=BlockPos{x=102, y=64, z=221}, worldReference=null) side west was found.
World loaded: true
Chunk loaded: true
Part container: org.cyclops.integrateddynamics.capability.partcontainer.PartContainerTileMultipartTicking@4f058240
Parts: {}
	at org.cyclops.integrateddynamics.capability.partcontainer.PartContainerDefault.getPartState(PartContainerDefault.java:177)
	at org.cyclops.integrateddynamics.api.part.PartPos.getPartData(PartPos.java:77)
	at org.cyclops.integrateddynamics.core.part.aspect.LazyAspectVariable.getAspectProperties(LazyAspectVariable.java:57)
	at org.cyclops.integrateddynamics.part.aspect.read.AspectReadBase$1.getValueLazy(AspectReadBase.java:79)
	at org.cyclops.integrateddynamics.core.part.aspect.LazyAspectVariable.getValue(LazyAspectVariable.java:49)
	at org.cyclops.integrateddynamics.core.evaluate.operator.OperatorBase$SafeVariablesGetter.getValue(OperatorBase.java:199)
	at org.cyclops.integrateddynamics.core.evaluate.operator.Operators.lambda$static$0(Operators.java:131)
	at org.cyclops.integrateddynamics.core.evaluate.operator.OperatorBase.evaluate(OperatorBase.java:138)
	at org.cyclops.integrateddynamics.core.evaluate.expression.LazyExpression.evaluate(LazyExpression.java:41)
	at org.cyclops.integrateddynamics.core.evaluate.expression.LazyExpression.getValue(LazyExpression.java:63)
	at org.cyclops.integrateddynamics.core.inventory.container.ContainerActiveVariableBase.func_75142_b(ContainerActiveVariableBase.java:46)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:324)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:642)
	at net.minecraft.world.World.func_72939_s(World.java:1734)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)
```
