### ISSUE TITLE
Crash - Exception in server tick loop

### ISSUE THREAD

**Issue by scotty9090** [CyclopsMC/IntegratedDynamics#735]
#### Issue type:

- :bug: Bug
____

#### Short description:
May or may not be related to: #734.  Crashing with the exception below.  I have the following setup:

- Storage Drawer Controller with an item interface attached.
- Three item importers connected to different inventories.  One of these is inside a Compact Machine (ID cable running into a Compact Machine tunnel).
EDIT:  I've removed the Compact Machine piping from the setup and the crash still occurs.
- Everything is on the same channel.

java.lang.NullPointerException: Exception in server tick loop
	at org.cyclops.commoncapabilities.ingredient.NBTBaseComparator.compare(NBTBaseComparator.java:43)
	at org.cyclops.commoncapabilities.ingredient.NBTBaseComparator.compare(NBTBaseComparator.java:39)
	at org.cyclops.commoncapabilities.ingredient.NBTBaseComparator.compare(NBTBaseComparator.java:22)
	at org.cyclops.commoncapabilities.api.capability.itemhandler.ItemMatch.areItemStackTagsEqual(ItemMatch.java:61)
	at org.cyclops.commoncapabilities.api.capability.itemhandler.ItemMatch.areItemStacksEqual(ItemMatch.java:53)
	at org.cyclops.commoncapabilities.ingredient.IngredientMatcherItemStack.matches(IngredientMatcherItemStack.java:52)

Full logs linked below.

The setup works well for a time, then crashes.

It's also worth noting that I need to brake / replace the cable running into the Compact Machine each time I start the world in order to get everything running.  I'm not sure if this is an issue with ID or with Compact Machines - please let me know if you'd like me to open a separate issue or if this is something I should be reporting to the Compact Machines author.

____

#### Versions:

Modpack: Enigmatica 2 Expert - 1.64d
Integrated Dynamics: 1.0.11
Integrated Tunnels: 1.6.8
Cyclops Core: 1.3.0
Forge: 14.23.5.2836
Minecraft: 1.12.2

#### Log file:

Latest.log: https://gist.github.com/scotty9090/94da9b560e36fd76fe1a467f2b3380c1

Crash Log: https://gist.github.com/scotty9090/0a341c154b64736d729b399488e4ca67

**Comment by rubensworks** [comment]
You're running several versions behind on the latest Common Capabilities release, this bug has been fixed there.

**Comment by scotty9090** [comment]
Thank you - I will report this to the E2E pack author so he can update CC.
