### ISSUE TITLE
Storage drawers crash

### ISSUE THREAD

**Issue by AssB0ys** [CyclopsMC/IntegratedDynamics#737]
#### Issue type:

- :bug: Bug

____

#### Short description:

There's definitely something going on with storage drawers compatibility. The game crashes on launch with the following error:

> [13:37:21] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$ServerTickEvent@4af9b705:
java.lang.ClassCastException: com.jaquadro.minecraft.storagedrawers.capabilities.DrawerItemHandler cannot be cast to net.minecraftforge.items.wrapper.InvWrapper
	at svenhjol.charm.base.ASMHooks.canInsertItemIntoShulkerBox(ASMHooks.java:102) ~[ASMHooks.class:?]
	at net.minecraftforge.items.ItemHandlerHelper.insertItem(ItemHandlerHelper.java:40) ~[ItemHandlerHelper.class:?]
	at org.cyclops.commoncapabilities.ingredient.storage.IngredientComponentStorageWrapperHandlerItemStack$ComponentStorageWrapper.insert(IngredientComponentStorageWrapperHandlerItemStack.java:139) ~[IngredientComponentStorageWrapperHandlerItemStack$ComponentStorageWrapper.class:?]
	at org.cyclops.commoncapabilities.ingredient.storage.IngredientComponentStorageWrapperHandlerItemStack$ComponentStorageWrapper.insert(IngredientComponentStorageWrapperHandlerItemStack.java:97) ~[IngredientComponentStorageWrapperHandlerItemStack$ComponentStorageWrapper.class:?]
	at org.cyclops.integrateddynamics.core.network.IngredientChannelAdapter.insert(IngredientChannelAdapter.java:133) ~[IngredientChannelAdapter.class:?]
	at org.cyclops.integratedcrafting.part.PartTypeInterfaceCrafting.insertIntoNetwork(PartTypeInterfaceCrafting.java:271) ~[PartTypeInterfaceCrafting.class:?]
	at org.cyclops.integratedcrafting.part.PartTypeInterfaceCrafting.update(PartTypeInterfaceCrafting.java:220) ~[PartTypeInterfaceCrafting.class:?]
	at org.cyclops.integratedcrafting.part.PartTypeInterfaceCrafting.update(PartTypeInterfaceCrafting.java:89) ~[PartTypeInterfaceCrafting.class:?]
	at org.cyclops.integrateddynamics.core.network.PartNetworkElement.update(PartNetworkElement.java:134) ~[PartNetworkElement.class:?]
	at org.cyclops.integrateddynamics.core.network.Network.update(Network.java:408) ~[Network.class:?]
	at org.cyclops.integrateddynamics.core.TickHandler.onTick(TickHandler.java:65) ~[TickHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_960_TickHandler_onTick_TickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:712) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:256) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
[13:37:21] [Server thread/ERROR] [FML]: Index: 14 Listeners:
[13:37:21] [Server thread/ERROR] [FML]: 0: NORMAL
[13:37:21] [Server thread/ERROR] [FML]: 1: ASM: class dan200.computercraft.shared.util.TickScheduler tick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[13:37:21] [Server thread/ERROR] [FML]: 2: ASM: class dan200.computercraft.shared.proxy.ComputerCraftProxyCommon$ForgeHandlers onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[13:37:21] [Server thread/ERROR] [FML]: 3: ASM: class com.feed_the_beast.mods.ftbbackups.FTBBackups onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[13:37:21] [Server thread/ERROR] [FML]: 4: ASM: net.minecraftforge.common.ForgeInternalHandler@46605225 onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[13:37:21] [Server thread/ERROR] [FML]: 5: ASM: mcjty.lostsouls.ForgeEventHandlers@7c8b4eab onTickEvent(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[13:37:21] [Server thread/ERROR] [FML]: 6: ASM: oreexcavation.handlers.EventHandler@6f3b7fc1 onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[13:37:21] [Server thread/ERROR] [FML]: 7: ASM: hellfirepvp.astralsorcery.common.auxiliary.tick.TickManager@1cddf9ee serverTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[13:37:21] [Server thread/ERROR] [FML]: 8: ASM: class thebetweenlands.common.handler.WorldEventHandler onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[13:37:21] [Server thread/ERROR] [FML]: 9: ASM: class thebetweenlands.common.capability.base.EntityCapabilityHandler onServerTickEvent(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[13:37:21] [Server thread/ERROR] [FML]: 10: ASM: thebetweenlands.common.world.biome.spawning.MobSpawnHandler@6fb92d3a onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[13:37:21] [Server thread/ERROR] [FML]: 11: ASM: class thebetweenlands.common.handler.EnvironmentEventOverridesHandler onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[13:37:21] [Server thread/ERROR] [FML]: 12: ASM: Block{minecraft:air} tickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[13:37:21] [Server thread/ERROR] [FML]: 13: ASM: org.cyclops.evilcraft.core.fluid.WorldSharedTankCache@3087e663 onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[13:37:21] [Server thread/ERROR] [FML]: 14: ASM: org.cyclops.integrateddynamics.core.TickHandler@17c6849a onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[13:37:21] [Server thread/ERROR] [FML]: 15: ASM: org.cyclops.integrateddynamics.core.NoteBlockEventReceiver@20509b1a onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[13:37:21] [Server thread/ERROR] [FML]: 16: LOWEST
[13:37:21] [Server thread/ERROR] [FML]: 17: ASM: class codechicken.lib.internal.CCLLog onTickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[13:37:21] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.ClassCastException: com.jaquadro.minecraft.storagedrawers.capabilities.DrawerItemHandler cannot be cast to net.minecraftforge.items.wrapper.InvWrapper
	at svenhjol.charm.base.ASMHooks.canInsertItemIntoShulkerBox(ASMHooks.java:102) ~[ASMHooks.class:?]
	at net.minecraftforge.items.ItemHandlerHelper.insertItem(ItemHandlerHelper.java:40) ~[ItemHandlerHelper.class:?]
	at org.cyclops.commoncapabilities.ingredient.storage.IngredientComponentStorageWrapperHandlerItemStack$ComponentStorageWrapper.insert(IngredientComponentStorageWrapperHandlerItemStack.java:139) ~[IngredientComponentStorageWrapperHandlerItemStack$ComponentStorageWrapper.class:?]
	at org.cyclops.commoncapabilities.ingredient.storage.IngredientComponentStorageWrapperHandlerItemStack$ComponentStorageWrapper.insert(IngredientComponentStorageWrapperHandlerItemStack.java:97) ~[IngredientComponentStorageWrapperHandlerItemStack$ComponentStorageWrapper.class:?]
	at org.cyclops.integrateddynamics.core.network.IngredientChannelAdapter.insert(IngredientChannelAdapter.java:133) ~[IngredientChannelAdapter.class:?]
	at org.cyclops.integratedcrafting.part.PartTypeInterfaceCrafting.insertIntoNetwork(PartTypeInterfaceCrafting.java:271) ~[PartTypeInterfaceCrafting.class:?]
	at org.cyclops.integratedcrafting.part.PartTypeInterfaceCrafting.update(PartTypeInterfaceCrafting.java:220) ~[PartTypeInterfaceCrafting.class:?]
	at org.cyclops.integratedcrafting.part.PartTypeInterfaceCrafting.update(PartTypeInterfaceCrafting.java:89) ~[PartTypeInterfaceCrafting.class:?]
	at org.cyclops.integrateddynamics.core.network.PartNetworkElement.update(PartNetworkElement.java:134) ~[PartNetworkElement.class:?]
	at org.cyclops.integrateddynamics.core.network.Network.update(Network.java:408) ~[Network.class:?]
	at org.cyclops.integrateddynamics.core.TickHandler.onTick(TickHandler.java:65) ~[TickHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_960_TickHandler_onTick_TickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:712) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:256) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
[13:37:21] [Server thread/WARN] [org.dimdev.utils.ModIdentifier]: Failed to identify net.minecraftforge.fml.common.eventhandler.ASMEventHandler_960_TickHandler_onTick_TickEvent (untransformed name: net.minecraftforge.fml.common.eventhandler.ASMEventHandler_960_TickHandler_onTick_TickEvent)

#### Steps to reproduce the problem:

I have a simple setup where on channel 0:
Interfaces are connected to Charm barrels which are accepting items from Hopping Bonsai pots
The extractor is extracting logWood to the Industrial Foregoing item splitter.
Channel 1 has:
Item Interface is on Storage Drawers drawer, the Item Importer imports charcoal from the Industrial Foregoing resourceful furnace. The crafting interface is on a crafting table and has a Quark block of charcoal recipe in it(crafting channel set to 1). An Item Exporter exports Quarks blocks of charcoal with the _craft_ set to _true_ to the Industrial Foregoing petrified fuel generator(it doesn't actually work I don't know why, maybe related to storage drawer).

One other detail I want to mention is that I noticed some errors in red(I use multimc) when I was shutting down the game yesterday, but I cannot find it now, but I remember it was something about FTB backups and it had something about integrated dynamics too that the interfaces were in an unloaded chunk, I am sorry I couldn't provide it now.

#### Versions:

- Common capabilities: 2.4.1
- Cyclops Core: 1.3.0
- Integrated Dynamics: 1.0.14
- Integrated Tunnels: 1.6.9
- Integrated Crafting: 1.0.7
- Integrated Terminals: 1.0.8
- Minecraft: 1.12.2
- Forge: 14.23.5.2838

#### Log file:

full log at: https://pastebin.com/96MuGbdk

**Comment by rubensworks** [comment]
> at svenhjol.charm.base.ASMHooks.canInsertItemIntoShulkerBox(ASMHooks.java:102)

Seems to be caused by this Charm mod. Can you report it on their issue tracker and link back here?

**Comment by AssB0ys** [comment]
This seems to be resolved in https://github.com/svenhjol/Charm/issues/87
