### ISSUE TITLE
Exporting things and crafting on demand.

### ISSUE THREAD

**Issue by AssB0ys** [CyclopsMC/IntegratedDynamics#738]
#### Issue type:

- :question: Question

____

#### Question:

There are a couple things that I want to know of. The first one is the description of a Crafting writer is not very clear in a guide book, what's its purpose exactly? Is it just another way to start a crafting job instead of a terminal?
And the other one I actually suspect that it is a bug.
So here are my setups:
The first one is https://i.imgur.com/32oRT2h.png
The chest with a charcoal has an interface on it, the chest that expects a charcoal block has an exporter with a charcoal block item variable in it and with _craft_ set to _true_. And then the crafting interface which has a charcoal block(from quark) recipe in it. This setup **works** but only if all the components operate on channel 0.
And then I have a similar setup - https://i.imgur.com/RFxGqFr.png and it doesn't work at all. It seems to work from time to time because when I was tinkering with it I saw a couple of charcoal blocks actually appear in the generator but not continiously, just occasionally I was noticing the amount of charcoal blocks was increasing when I opened the generator GUI. And I've really tried everything - the channels, nbt, damage, amount check and everything. Also it doesn't actually matter if there's a chest with charcoal or a storage drawer - because at first I thought it was the Storage Drawers mod that was causing problems.

**Comment by rubensworks** [comment]
> Crafting writer is not very clear in a guide book, what's its purpose exactly?
> Is it just another way to start a crafting job instead of a terminal?

Yep! It's a way to start crafting jobs automatically based on variable cards.

> This setup works but only if all the components operate on channel 0.

That's normal, things have to be in the same channel to allow communication between them.

> And then I have a similar setup

I would suggest either replacing the machine or the storage drawer with a chest. Based on that, you'll be able to determine which one is causing problems. Depending on the outcome on that, you can report a bug in the appropriate issue tracker.

**Comment by AssB0ys** [comment]
> That's normal, things have to be in the same channel to allow communication between them

Yes I see that I couldn't explain it well. The setup doesn't work if all the components operate all on _the same_ channel but other than 0.

But now that I have this crash report:
> java.lang.ClassCastException: com.jaquadro.minecraft.storagedrawers.capabilities.DrawerItemHandler cannot be cast to net.minecraftforge.items.wrapper.InvWrapper
    at svenhjol.charm.base.ASMHooks.canInsertItemIntoShulkerBox(ASMHooks.java:102)
    at net.minecraftforge.items.ItemHandlerHelper.insertItem(ItemHandlerHelper.java:40)
    at org.cyclops.commoncapabilities.ingredient.storage.IngredientComponentStorageWrapperHandlerItemStack$ComponentStorageWrapper.insert(IngredientComponentStorageWrapperHandlerItemStack.java:139)
    at org.cyclops.commoncapabilities.ingredient.storage.IngredientComponentStorageWrapperHandlerItemStack$ComponentStorageWrapper.insert(IngredientComponentStorageWrapperHandlerItemStack.java:97)
    at org.cyclops.integrateddynamics.core.network.IngredientChannelAdapter.insert(IngredientChannelAdapter.java:133)
    at org.cyclops.integratedcrafting.part.PartTypeInterfaceCrafting.insertIntoNetwork(PartTypeInterfaceCrafting.java:271)
    at org.cyclops.integratedcrafting.part.PartTypeInterfaceCrafting.update(PartTypeInterfaceCrafting.java:220)
    at org.cyclops.integratedcrafting.part.PartTypeInterfaceCrafting.update(PartTypeInterfaceCrafting.java:89)
    at org.cyclops.integrateddynamics.core.network.PartNetworkElement.update(PartNetworkElement.java:134)
    at org.cyclops.integrateddynamics.core.network.Network.update(Network.java:408)
    at org.cyclops.integrateddynamics.core.TickHandler.onTick(TickHandler.java:65)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_960_TickHandler_onTick_TickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:712)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:256)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)

I think the problem is much deeper and it is definitely related to storage drawers this time. I also noticed the icons in my inventory were shifting around - not the actual items but the icons, I was trying to use a logic programmer turns out it was actually a sleeping bag from another mod. I also noticed this same weird behaviour when I was playing a enigmatica 2 expert modpack and was tinkering with the Integrated Dynamics networks **and** Storage Drawers too.
This will take me some time though to file a proper bug report for this, because I do not know the actual direction too look at when reproducing this.

**Comment by rubensworks** [comment]
> I also noticed the icons in my inventory were shifting around

That's really weird...

That would explain your crash though, because something is `null` there, that should not even be possible to be `null`. I suspect a mod you are using is somehow shifting items around in illegal ways, which causes things to misbehave, and crash.

But indeed, if you have more details, be sure to open a bug report.
