### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by Mercurious1** [CyclopsMC/IntegratedDynamics#766]
#### Issue type:

- :bug: Bug

____

#### Short description:
Crashed on load 

#### Steps to reproduce the problem:
Load game with IntegratedDynamics-1.12.2-1.0.13.jar and CyclopsCore-1.12.2-1.5.0.jar

1. ...

#### Expected behaviour:

____

#### Versions:
IntegratedDynamics-1.12.2-1.0.13.jar and CyclopsCore-1.12.2-1.5.0.jar

- This mod: 1.0.13
- Minecraft: 1.12.2
- Forge: 2836

#### Log file:
[02:07:53] [Client thread/FATAL] [VanillaFix]: Minecraft ran into a problem! Report saved to: D:\Technosophy\Github\PrivateTechnosophy-Client\crash-reports\crash-2019-08-08_02.07.52-client.txt
---- Minecraft Crash Report ----
// Don't do that.

Time: 2019-08-08 02:07:53 PDT
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Integrated Dynamics (integrateddynamics)
Caused by: java.lang.NoSuchMethodError: org.cyclops.cyclopscore.infobook.InfoBook.<init>(Lorg/cyclops/cyclopscore/init/ModBase;I)V
    at org.cyclops.integrateddynamics.infobook.OnTheDynamicsOfIntegrationBook.<init>(OnTheDynamicsOfIntegrationBook.java:253)
    at org.cyclops.integrateddynamics.infobook.OnTheDynamicsOfIntegrationBook.getInstance(OnTheDynamicsOfIntegrationBook.java:258)
    at org.cyclops.integrateddynamics.IntegratedDynamics.preInit(IntegratedDynamics.java:233)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by rubensworks** [comment]
Please update to the latest ID version (1.0.18)
