### ISSUE TITLE
java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes

### ISSUE THREAD

**Issue by Routhinator** [CyclopsMC/IntegratedDynamics#794]
#### Issue type:

- :bug: Bug

____

#### Short description:

Attempting to craft a piston in the ID Storage Terminal causes a client disconnect with the error:

```
[08:37:41] [Netty Epoll Client IO #1/ERROR] [FML]: NetworkDispatcher exception
java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes
	at net.minecraft.network.play.client.CPacketCustomPayload.<init>(CPacketCustomPayload.java:28) ~[lh.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.toC17Packet(FMLProxyPacket.java:142) ~[FMLProxyPacket.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.write(NetworkDispatcher.java:533) ~[NetworkDispatcher.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at net.minecraft.network.NetworkManager$4.run(NetworkManager.java:245) [gw$4.class:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
[08:37:41] [Netty Epoll Client IO #1/INFO] [EnderCore]: Reset configs to client values for com.enderio.core.common.config.ConfigHandler
[08:37:41] [Netty Epoll Client IO #1/INFO] [mcjtylib_ng]: Client disconnected from server

```

#### Steps to reproduce the problem:

1. This one seems to be based on some awkward level of system complexity, items in the system and only very specific recipes. And the only recipe I know of that does it every time is a piston which uses very basic items. I can craft dozens of other recipes without error.

One possible suspect is the YABBA barrel array storing many of my items. I have given the barrels infinite upgrades yet somehow ID determines a storage limit. I'm wondering if that is messing with things somehow.

I do not have any bags in the system or any items that contain items. Just barrels, chests.

___

#### Versions:

- This mod: 1.1.1
- Minecraft: 1.12.2
- Forge: 14.23.5.2847

#### Log file:
See output above.

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!

**Comment by Routhinator** [comment]
Please let me know if you need anything else like a screenshot of the system or if you want to jump on the server and see the setup in realtime.

**Comment by Pultex** [comment]
yeah YABBA barrels have been bugged for a bit, not sure if they fixed it, but the anti barrel will in time make world corruption.

**Comment by TomyLobo** [comment]
@Routhinator This mod might be a workaround until this is fixed:
https://www.curseforge.com/minecraft/mc-mods/bigger-packets-please
I use it, too, haven't had a single problem with it.

And @Pultex, would you stop commenting on every issue unless you have something to contribute to it?
This issue is about packet size, not world corruption.

**Comment by rubensworks** [comment]
Unfortunately, I'm not able to reproduce this problem myself.

If anyone encounters this problem and can share a description on how to reproduce the problem (without any other mods installed), please comment on this issue.

**Comment by komega13** [comment]
Running Sevtech 3.1.2 I had a similar issue attempting to craft a simple piston into a Refined Storage crafting grid when importing items via the "+" button on JEI interface (trying 2 times with same exact result) = java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes
My setup is about 20 obsidian chest linked to the craft grid, these chest contain a lot of stuff would the probleme may come from here ? Any help appreciated and thanks to the devs for your work

**Comment by TomyLobo** [comment]
@komega13 refined storage? is integrated dynamics involved at all in your issue?

**Comment by komega13** [comment]
@TomyLobo I don't think integrated dynamic is involve as it was with refined storage but it's a very similar issue (attempting to craft a piston on a mod grid craft from JEI recipe) mayby the problem comes from JEI
