### ISSUE TITLE
Network don't work anymore and server crash while attempting to remove cable

### ISSUE THREAD

**Issue by ghost** [CyclopsMC/IntegratedDynamics#799]
#### Issue type:

- :bug: Bug

____

#### Short description:

After logging into the world, terminals won't show inventory connected to it anymore, item won't export or import neither.
I've tried to replace the cables but the server crashed while attempting to break it with the wrench.

#### Steps to reproduce the problem:

I don't know what caused this issue, or what could have change between my gaming sessions
1.Install Volcano Block modpack v1.0.35
2. Logging into the world
3.Checking the terminals
4.Breaking a cable with a wrench

____

#### Versions:

- This mod: 
Integrated Dynamics : 1.12.2-1.1.1
Integrated Terminals : 1.12.2-1.0.13
- Minecraft: 1.12.2
- Forge: 14.23.5.2847

#### Log file:

https://pastebin.com/UbjVexQw

**Comment by GreyMario** [comment]
...Where is the _stack trace_? Shouldn't there be a stack trace in the error log?

**Comment by rubensworks** [comment]
@Animaly0 It indeed looks like your stacktrace is missing from the log file. Could you share the full crashlog file or Forge log?

**Comment by ghost** [comment]
[2020-01-01-1.log](https://github.com/CyclopsMC/IntegratedDynamics/files/4015910/2020-01-01-1.log)

I could'nt paste the whole file on pastebin, that's why, is it working like that ?

**Comment by rubensworks** [comment]
Thanks!

Note to self:
```
java.lang.ClassCastException: org.cyclops.integrateddynamics.core.evaluate.variable.ValueObjectTypeItemStack$ValueItemStack incompatible with org.cyclops.integrateddynamics.core.evaluate.variable.ValueObjectTypeEntity$ValueEntity
	at org.cyclops.integrateddynamics.core.evaluate.operator.Operators.lambda$static$121(Operators.java:1856) ~[Operators.class:?]
	at org.cyclops.integrateddynamics.core.evaluate.operator.Operators$$Lambda$682.000000001BC6B860.evaluate(Unknown Source) ~[?:?]
	at org.cyclops.integrateddynamics.core.evaluate.operator.OperatorBase.evaluate(OperatorBase.java:148) ~[OperatorBase.class:?]
	at org.cyclops.integrateddynamics.core.evaluate.expression.LazyExpression.evaluate(LazyExpression.java:41) ~[LazyExpression.class:?]
	at org.cyclops.integrateddynamics.core.evaluate.expression.LazyExpression.getValue(LazyExpression.java:63) ~[LazyExpression.class:?]
	at org.cyclops.integrateddynamics.core.part.panel.PartTypePanelVariableDriven.update(PartTypePanelVariableDriven.java:127) ~[PartTypePanelVariableDriven.class:?]
	at org.cyclops.integrateddynamics.core.part.panel.PartTypePanelVariableDriven.update(PartTypePanelVariableDriven.java:57) ~[PartTypePanelVariableDriven.class:?]
	at org.cyclops.integrateddynamics.core.network.PartNetworkElement.update(PartNetworkElement.java:135) ~[PartNetworkElement.class:?]
	at org.cyclops.integrateddynamics.core.network.Network.update(Network.java:410) ~[Network.class:?]
	at org.cyclops.integrateddynamics.core.TickHandler.onTick(TickHandler.java:65) ~[TickHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1007_TickHandler_onTick_TickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:819) [?:1.8.0_222]
```

Seems to be a catchable type error.

**Comment by rubensworks** [comment]
Apologies for the long delay, but I'm unable to reproduce this problem with the given information, or make any sense of the stack trace.

@Animaly0 Could you share the logic operations that resulted in this crash? It has something to do with the version of items <-> entities.
