### ISSUE TITLE
[1.10.2][0.6.3] Opening Logic Programmer GUI crashes Minecraft

### ISSUE THREAD

**Issue by Belgabor** [CyclopsMC/IntegratedDynamics#84]
Opening the Logic Programmer GUI crashes the game. 

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.0-59.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.3.jar)
  Default Options (DefaultOptions_1.10.2-6.1.5.jar)
  ForgelinPlugin (Forgelin-1.1.0.jar)
  literalascension (literalascension-1.10.2-1.0.0.0.jar)
  LoadingPlugin (ChunkAnimator-MC1.9.4-1.2.jar)
  BetterFoliageLoader (BetterFoliage-MC1.10-2.1.1.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  llibrary (llibrary-1.7.1-1.10.2.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.4.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 11/22/16 2:24 AM
Description: Rendering screen

java.lang.IllegalArgumentException: fromIndex(135) > toIndex(40)
	at java.util.ArrayList.subListRangeCheck(Unknown Source)
	at java.util.ArrayList.subList(Unknown Source)
	at org.cyclops.cyclopscore.client.gui.container.ScrollingGuiContainer.func_73863_a(ScrollingGuiContainer.java:162)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList.subListRangeCheck(Unknown Source)
	at java.util.ArrayList.subList(Unknown Source)
	at org.cyclops.cyclopscore.client.gui.container.ScrollingGuiContainer.func_73863_a(ScrollingGuiContainer.java:162)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)

-- Screen render details --
Details:
	Screen name: org.cyclops.integrateddynamics.client.gui.GuiLogicProgrammer
	Mouse location: Scaled: (480, 257). Absolute: (960, 513)
	Screen size: Scaled: (960, 514). Absolute: (1920, 1027). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityPlayerSP['Belgabor'/5544316, l='MpServer', x=-231.35, y=68.00, z=295.73], EntityOtherPlayerMP['Finvaara'/5485619, l='MpServer', x=-235.26, y=68.00, z=297.09]]
	Chunk stats: MultiplayerChunkCache: 225, 225
	Level seed: 0
	Level generator: ID 06 - RTG, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-46,64,25), Chunk: (at 2,4,9 in -3,1; contains blocks -48,0,16 to -33,255,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 15983935 game time, 16813931 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 6 total; [EntityOtherPlayerMP['Finvaara'/5485619, l='MpServer', x=-235.26, y=68.00, z=297.09], EntityPig['Pig'/5478082, l='MpServer', x=-178.30, y=64.00, z=364.53], EntityMobCow5['Ayrshire'/5477479, l='MpServer', x=-275.21, y=118.00, z=323.58], EntityPlayerSP['Belgabor'/5544316, l='MpServer', x=-231.35, y=68.00, z=295.73], EntityOtherPlayerMP['Finvaara'/5485619, l='MpServer', x=-235.26, y=68.00, z=297.09], EntityBat['Bat'/5544429, l='MpServer', x=-179.47, y=22.87, z=314.16]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_102, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1357026728 bytes (1294 MB) / 5650579456 bytes (5388 MB) up to 6355222528 bytes (6060 MB)
	JVM Flags: 26 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:ParallelGCThreads=10
	IntCache: cache: 1, tcache: 31, allocated: 9, tallocated: 61
	FML: MCP 9.32 Powered by Forge 12.18.2.2125 128 mods loaded, 128 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2125.jar) 
	UCHIJA	Forge{12.18.2.2125} [Minecraft Forge] (forge-1.10.2-12.18.2.2125.jar) 
	UCHIJA	cei{1.3} [Chunk Edge Indicator] (1.10-chunkedgeindicator-1.3.jar) 
	UCHIJA	thirdperson{1.1.0} [ThirdPersonEverything] (3rdPersonEverything-1.1.0.jar) 
	UCHIJA	actuallyadditions{1.10.2-r71} [Actually Additions] (ActuallyAdditions-1.10.2-r71.jar) 
	UCHIJA	ForgeEndertech{1.1.3.0} [Forge Endertech] (ForgeEndertech-1.10.2-1.1.3.0.jar) 
	UCHIJA	AdChimneys{1.10.2-1.1.4.0} [Advanced Chimneys] (AdChimneys-1.10.2-1.1.4.0.jar) 
	UCHIJA	additionalbanners{1.3.0.22} [Additional Banners] (AdditionalBanners-1.10.2-1.3.0.22.jar) 
	UCHIJA	Baubles{1.3.5} [Baubles] (Baubles-1.10.2-1.3.5.jar) 
	UCHIJA	Botania{r1.9-338} [Botania] (Botania r1.9-338.jar) 
	UCHIJA	AkashicTome{1.0-5} [Akashic Tome] (AkashicTome-1.0-5.jar) 
	UCHIJA	mcmultipart{1.3.0} [MCMultiPart] (MCMultiPart-1.3.0-universal.jar) 
	UCHIJA	CharsetLib{0.3.0-pre15} [‽] (Charset-0.3.0-pre15.jar) 
	UCHIJA	CharsetGates{0.3.0-pre15} [&] (Charset-0.3.0-pre15.jar) 
	UCHIJA	analoguers{1.1} [AnalogueRS] (AnalogueRS-1.1.jar) 
	UCHIJA	immersiveengineering{0.10-48} [Immersive Engineering] (ImmersiveEngineering-0.10-48.jar) 
	UCHIJA	JEI{3.13.3.376} [Just Enough Items] (jei_1.10.2-3.13.3.376.jar) 
	UCHIJA	appleskin{1.0.4} [AppleSkin] (AppleSkin-mc1.10.2-1.0.4.jar) 
	UCHIJA	architecturecraft{1.7.0} [ArchitectureCraft] (ArchitectureCraft-1.7.0-mc1.10.2.jar) 
	UCHIJA	atlcraft{1.10.2-Ver1.5} [ATLCraft Candles Mod] (ATLCraftCandlesMod(MC1.10.2-Ver1.5).jar) 
	UCHIJA	Quark{r1.0-59} [Quark] (Quark-r1.0-59.jar) 
	UCHIJA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJA	babyanimals{1.9.4} [Baby Animals Model Swapper] (BabyAnimals-1.9.4.jar) 
	UCHIJA	BaublesHud{3.2.0} [Baubles-Hud] (BaublesHud-1.10.2-3.2.0.jar) 
	UCHIJA	bdlib{1.12.2.17} [BD Lib] (bdlib-1.12.2.17-mc1.10.2.jar) 
	UCHIJA	BetterAchievements{0.3.2.35} [Better Achievements] (BetterAchievements-1.10.2-0.3.2.35.jar) 
	UCHIJA	betteragriculture{1.0} [Better Agriculture] (BetterAgriculture-1.10.2-1.0.jar) 
	UCHIJA	BetterFoliage{2.1.1} [Better Foliage] (BetterFoliage-MC1.10-2.1.1.jar) 
	UCHIJA	bettertitlescreen{1.2e} [Better Title Screen] (BetterTitleScreen-1.10.2-1.2e.jar) 
	UCHIJA	BlockDispenser{1.0} [BlockDispenser] (BlockDispenser-1.0-1.jar) 
	UCHIJA	infinitylib{1.10.2-0.2.1} [InfinityLib] (infinitylib-0.2.1.jar) 
	UCHIJA	boatlantern{1.10.2-0.2.1} [Lantern] (boatlantern-0.2.1.jar) 
	UCHIJA	Chameleon{1.10-2.1.8} [Chameleon] (Chameleon-1.10-2.1.8.jar) 
	UCHIJA	CharsetAudio{0.3.0-pre15} [♫] (Charset-0.3.0-pre15.jar) 
	UCHIJA	CharsetCarts{0.3.0-pre15} [U] (Charset-0.3.0-pre15.jar) 
	UCHIJA	CharsetDecoration{0.3.0-pre15} [⚿] (Charset-0.3.0-pre15.jar) 
	UCHIJA	CharsetDrama{0.3.0-pre15} [!] (Charset-0.3.0-pre15.jar) 
	UCHIJA	CharsetFarming{0.3.0-pre15} [;] (Charset-0.3.0-pre15.jar) 
	UCHIJA	CharsetPipes{0.3.0-pre15} [|] (Charset-0.3.0-pre15.jar) 
	UCHIJA	CharsetStorage{0.3.0-pre15} [#] (Charset-0.3.0-pre15.jar) 
	UCHIJA	CharsetTweaks{0.3.0-pre15} [*] (Charset-0.3.0-pre15.jar) 
	UCHIJA	CharsetWires{0.3.0-pre15} [+] (Charset-0.3.0-pre15.jar) 
	UCHIJA	CharsetWrench{0.3.0-pre15} [/] (Charset-0.3.0-pre15.jar) 
	UCHIJA	chisel{MC1.10.2-0.0.7.3} [Chisel] (Chisel-MC1.10.2-0.0.7.3.jar) 
	UCHIJA	chiselsandbits{12.7} [Chisels & Bits] (chiselsandbits-12.7.jar) 
	UCHIJA	ChunkAnimator{1.2} [Chunk Animator] (ChunkAnimator-MC1.9.4-1.2.jar) 
	UCHIJA	shadowmc{3.5.0} [ShadowMC] (ShadowMC-1.10.2-3.6.0.jar) 
	UCHIJA	clipboard{@VERSION@} [Clipboard] (Clipboard-1.10.2-1.1.0.jar) 
	UCHIJA	cyclopscore{0.8.1} [Cyclops Core] (CyclopsCore-1.9.4-0.8.1.jar) 
	UCHIJA	commoncapabilities{1.2.1} [CommonCapabilities] (CommonCapabilities-1.9.4-1.2.1.jar) 
	UCHIJA	cookingforblockheads{4.2.26} [Cooking for Blockheads] (CookingForBlockheads_1.10.2-4.2.26.jar) 
	UCHIJA	cosmeticarmorreworked{1.10.2-v2a} [CosmeticArmorReworked] (CosmeticArmorReworked-1.10.2-v2a.jar) 
	UCHIJA	craftablenametags{1.4} [Craftable Name Tags] (craftablenametags-1.4.jar) 
	UCHIJA	MineTweaker3{3.0.14} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.15.jar) 
	UCHIJA	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.10.2-3.0.15.jar) 
	UCHIJA	customstartinggear{1.0.0} [Custom Starting Gear] (CustomStartingGear-1.10.2-1.0.0.5-universal.jar) 
	UCHIJA	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.3.5_1.10.2.jar) 
	UCHIJA	props{2.3.4} [Decocraft] (Decocraft-2.3.5_1.10.2.jar) 
	UCHIJA	defaultoptions{6.1.5} [Default Options] (DefaultOptions_1.10.2-6.1.5.jar) 
	UCHIJA	defaultworldgenerator-port{1.9.4-0.4} [Default World Generator] (DefaultWorldGenerator-port-1.9.4-0.4.jar) 
	UCHIJA	StorageDrawers{1.10.2-3.4.6} [Storage Drawers] (StorageDrawers-1.10.2-3.4.6.jar) 
	UCHIJA	bitdrawers{0.33} [Drawers & Bits] (DrawersBits-1.10.2-0.33.jar) 
	UCHIJA	druidry{2016.9.26-1.9.4} [ǲDruidry] (druidry(2016.9.26)(1.9.4).jar) 
	UCHIJA	shetiphiancore{3.3.3} [ShetiPhian-Core] (shetiphiancore-1.10.0-3.3.4.jar) 
	UCHIJA	endertanks{1.4.5} [EnderTanks] (endertanks-1.10.0-1.4.5.jar) 
	UCHIJA	EnderZoo{1.10-1.2.3.43} [Ender Zoo] (EnderZoo-1.10-1.2.3.43.jar) 
	UCHIJA	ExtraBitManipulation{1.10.2-2.1.0} [Extra Bit Manipulation] (ExtraBitManipulation-1.10.2-2.1.0.jar) 
	UCHIJA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-alpha-1.2.2.jar) 
	UCHIJA	forestry{5.2.16.327} [Forestry] (forestry_1.10.2-5.2.16.327.jar) 
	UCHIJA	fw{1.3.0} [Fullscreen Windowed] (FullscreenWindowed-1.10.2-1.3.0b.jar) 
	UCHIJA	gearswap{1.2.7} [Gear Swapper] (gearswap-1.10-1.2.7.jar) 
	UCHIJA	gendustry{1.6.4.24} [GenDustry] (gendustry-1.6.4.24-mc1.10.2.jar) 
	UCHIJA	giacomosfoundry{1.3.6} [Giacomo's Foundry] (GiacomosFoundry1.10.2-1.3.6.jar) 
	UCHIJA	grapplemod{1.10.2-v8} [Grappling hook mod] (grapplemod-1.10-v8.jar) 
	UCHIJA	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.2-45.jar) 
	UCHIJA	hatchery{1.0.0} [Hatchery] (hatchery-1.10.2-0.1.11.jar) 
	UCHIJA	helpertools{v3.0c} [HelperTools] (HelperTools-1.10.2-v3.0c.jar) 
	UCHIJA	integrateddynamics{0.6.3} [Integrated Dynamics] (IntegratedDynamics-1.10.2-0.6.3.jar) 
	UCHIJA	integratedtunnels{1.0.0} [Integrated Tunnels] (IntegratedTunnels-1.10.2-1.0.0.jar) 
	UCHIJA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJA	ironbackpacks{1.10.2-2.2.15} [Iron Backpacks] (IronBackpacks-1.10.2-2.2.15.jar) 
	UCHIJA	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UCHIJA	jeibees{0.9.0.4} [JEI Bees] (jeibees-0.9.0.4-mc1.10.2.jar) 
	UCHIJA	journeymap{1.10.2-5.3.0b2} [JourneyMap] (journeymap-1.10.2-5.3.0b2-unlimited.jar) 
	UCHIJA	jeresources{0.5.7.87} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.7.87.jar) 
	UCHIJA	llibrary{1.7.1} [LLibrary] (llibrary-1.7.1-1.10.2.jar) 
	UCHIJA	literalascension{1.10.2-1.0.0.0} [Literal Ascension] (literalascension-1.10.2-1.0.0.0.jar) 
	UCHIJA	llor{1.1.0-mc[1.9-1.10.2]} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.0-mc[1.9-1.10.2].jar) 
	UCHIJA	login_shield{1.10.2-17-g972e27d} [Login Shield] (Login_Shield-1.10.2-17-g972e27d.jar) 
	UCHIJA	mtrm{1.2.1.20} [MineTweakerRecipeMaker] (MineTweakerRecipeMaker-1.10.2-1.2.1.20.jar) 
	UCHIJA	mithwoodforest{RMF1.03} [Rainbeau's Mithwood Forest] (MithwoodForest-RMF1.03-MC1.10.2.jar) 
	UCHIJA	mobends{0.22.5} [Mo'Bends] (mobends-0.22.5_for_MC-1.10.2.jar) 
	UCHIJA	craftelytra{1.1} [Craftable Elytra] (modid-1.1-1.10.2.jar) 
	UCHIJA	ModNameTooltip{1.6.0} [Mod Name Tooltip] (modnametooltip_1.10.2-1.6.0.jar) 
	UCHIJA	morebees{1.10.2-1.1.4.1} [More Bees] (morebees-1.10.2-1.1.4.1.jar) 
	UCHIJA	morematerials{1.10.2-1.9.20160723.0} [More Materials] (morematerials-1.10.2-1.9.20160723.0.jar) 
	UCHIJA	Morpheus{1.10.2-3.1.9} [Morpheus] (Morpheus-1.10.2-3.1.9.jar) 
	UCHIJA	mousetweaks{2.6.4} [Mouse Tweaks] (MouseTweaks-2.6.4-mc1.10.2.jar) 
	UCHIJA	multibeds{1.2.2} [Multi-Beds] (multibeds-1.10.0-1.2.2.jar) 
	UCHIJA	multistorage{1.2.8} [Multi-Storage] (multistorage-1.10.0-1.2.8.jar) 
	UCHIJA	naturescompass{1.2.0} [Nature's Compass] (NaturesCompass-1.10.2-1.2.0.jar) 
	UCHIJA	netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.9.4-4.0.1.jar) 
	UCHIJA	recipehandler{0.6} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.6(1.10.2).jar) 
	UCHIJA	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	UCHIJA	placeableitems{3.0.3.1} [Placeable Items Mod] (placeableitems-3.0.3.1.jar) 
	UCHIJA	railcraft{10.0.0} [Railcraft] (Railcraft_1.10.2-10.0.0.jar) 
	UCHIJA	rangedpumps{0.3} [Ranged Pumps] (rangedpumps-0.3.jar) 
	UCHIJA	ReAuth{3.2} [ReAuth] (ReAuth-3.2.jar) 
	UCHIJA	roots{0.204} [Roots] (roots-1.10.2-0.204.0.jar) 
	UCHIJA	RTG{4.1.1.7} [Realistic Terrain Generation] (RTG-1.10.2-4.1.1.7.jar) 
	UCHIJA	SilentLib{1.1.0} [Silent Lib] (SilentLib-1.10.2-1.1.0-23.jar) 
	UCHIJA	SilentGems{2.1.4} [Silent's Gems] (SilentsGems-1.10.2-2.1.4-83.jar) 
	UCHIJA	sgextraparts{1.1.1} [Silent's Gems: Extra Parts] (SGExtraParts-1.10.2-1.1.1-6.jar) 
	UCHIJA	simpleharvest{1.06} [Simple Harvest] (simpleharvest-1.10.2-1.06.jar) 
	UCHIJA	supercraftingframe{1.2.1.88} [Super Crafting Frame] (supercraftingframe-1.10.2-1.2.1.88.jar) 
	UCHIJA	thutcore{3.8.0} [ThutCore] (thutcore-3.8.0.jar) 
	UCHIJA	thuttech{4.0.10} [Thut's Tech] (thuttech-4.0.10.jar) 
	UCHIJA	tombmanygraves{1.10.2-2.1.13} [Tomb Many Graves] (TombManyGraves-1.10.2-2.1.13.jar) 
	UCHIJA	totemic{1.9.4-0.7.9.1} [Totemic] (Totemic-1.9.4-0.7.9.1.jar) 
	UCHIJA	tumbleweed{1.10-0.3} [Tumbleweed] (tumbleweed-1.10-0.3.jar) 
	UCHIJA	vc{v3.1.5a-mc1.10.2} [ViesCraft] (ViesCraft-3.1.5a-mc1.10.2.jar) 
	UCHIJA	waddles{0.5.0} [Waddles] (Waddles-1.10.2-0.5.0.jar) 
	UCHIJA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJA	WailaHarvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.10.2-1.1.9.jar) 
	UCHIJA	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.1.213.jar) 
	UCHIJA	wawla{2.3.1.213} [What Are We Looking At] (Wawla-1.10.2-2.3.1.213.jar) 
	UCHIJA	fluidity{6.1.3} [Fluidity] (Fluidity-6.1.3.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.0-59.jar)
  vazkii.quark.base.asm.ClassTransformer
ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.3.jar)
  team.chisel.common.asm.ChiselTransformer
Default Options (DefaultOptions_1.10.2-6.1.5.jar)
  net.blay09.mods.defaultoptions.coremod.DefaultOptionsClassTransformer
ForgelinPlugin (Forgelin-1.1.0.jar)
  
literalascension (literalascension-1.10.2-1.0.0.0.jar)
  com.jamieswhiteshirt.literalascension.core.patcher.LiteralAscensionRuntimePatcher
LoadingPlugin (ChunkAnimator-MC1.9.4-1.2.jar)
  lumien.chunkanimator.asm.ClassTransformer
BetterFoliageLoader (BetterFoliage-MC1.10-2.1.1.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
llibrary (llibrary-1.7.1-1.10.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.4.jar)
  shetiphian.core.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 368.81' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	List of loaded APIs: 
		* actuallyadditionsapi (27) from ActuallyAdditions-1.10.2-r71.jar
		* Baubles|API (1.3.1.1) from Baubles-1.10.2-1.3.5.jar
		* BetterAchievements|API (0.3.2.35) from BetterAchievements-1.10.2-0.3.2.35.jar
		* BotaniaAPI (79) from AkashicTome-1.0-5.jar
		* CharsetAPI (0.1) from Charset-0.3.0-pre15.jar
		* CharsetAPI|Audio (0.0) from Charset-0.3.0-pre15.jar
		* CharsetAPI|Lib (0.2) from Charset-0.3.0-pre15.jar
		* CharsetAPI|Pipes (0.3) from Charset-0.3.0-pre15.jar
		* CharsetAPI|Storage (0.1) from Charset-0.3.0-pre15.jar
		* CharsetAPI|Tape (0.0) from Charset-0.3.0-pre15.jar
		* CharsetAPI|Wires (0.3) from Charset-0.3.0-pre15.jar
		* ChiselAPI (0.0.1) from Chisel-MC1.10.2-0.0.7.3.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.10.2-0.0.7.3.jar
		* ChiselsAndBitsAPI (12.5.0) from chiselsandbits-12.7.jar
		* CoFHAPI (1.8.9R1.2.0B1) from ActuallyAdditions-1.10.2-r71.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from Railcraft_1.10.2-10.0.0.jar
		* commoncapabilities|api (0.0.1) from CommonCapabilities-1.9.4-1.2.1.jar
		* CSLib|API (0.3.0) from Decocraft-2.3.5_1.10.2.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.10.2-5.2.16.327.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.10.2-5.2.16.327.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.10.2-5.2.16.327.jar
		* ForestryAPI|climate (2.1.0) from forestry_1.10.2-5.2.16.327.jar
		* ForestryAPI|core (5.1.0) from forestry_1.10.2-5.2.16.327.jar
		* ForestryAPI|farming (2.1.0) from forestry_1.10.2-5.2.16.327.jar
		* ForestryAPI|food (1.1.0) from forestry_1.10.2-5.2.16.327.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.10.2-5.2.16.327.jar
		* ForestryAPI|genetics (4.7.1) from forestry_1.10.2-5.2.16.327.jar
		* ForestryAPI|greenhouse (5.2.0) from forestry_1.10.2-5.2.16.327.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.10.2-5.2.16.327.jar
		* ForestryAPI|lepidopterology (1.3.0) from forestry_1.10.2-5.2.16.327.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.10.2-5.2.16.327.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.10.2-5.2.16.327.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.10.2-5.2.16.327.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.10.2-5.2.16.327.jar
		* ForestryAPI|world (2.1.0) from forestry_1.10.2-5.2.16.327.jar
		* gendustryAPI (2.3.0) from gendustry-1.6.4.24-mc1.10.2.jar
		* Guide-API|API (1.10.2-2.0.2-45) from Guide-API-1.10.2-2.0.2-45.jar
		* ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.10-48.jar
		* ImmersiveEngineering|ImmersiveFluxAPI (1.0) from ImmersiveEngineering-0.10-48.jar
		* integrateddynamics|api (0.2.0) from IntegratedDynamics-1.10.2-0.6.3.jar
		* IronBackpacks|API (0.5) from IronBackpacks-1.10.2-2.2.15.jar
		* jeresources|API (0.5.7.87) from JustEnoughResources-1.10.2-0.5.7.87.jar
		* journeymap|client-api (1.3-SNAPSHOT) from journeymap-1.10.2-5.3.0b2-unlimited.jar
		* journeymap|client-api-display (1.3-SNAPSHOT) from journeymap-1.10.2-5.3.0b2-unlimited.jar
		* journeymap|client-api-event (1.3-SNAPSHOT) from journeymap-1.10.2-5.3.0b2-unlimited.jar
		* journeymap|client-api-model (1.3-SNAPSHOT) from journeymap-1.10.2-5.3.0b2-unlimited.jar
		* journeymap|client-api-util (1.3-SNAPSHOT) from journeymap-1.10.2-5.3.0b2-unlimited.jar
		* JustEnoughItemsAPI (4.10.1) from jei_1.10.2-3.13.3.376.jar
		* railcraft:API|core (2.0.0) from Railcraft_1.10.2-10.0.0.jar
		* RailcraftAPI|bore (2.0.0) from Railcraft_1.10.2-10.0.0.jar
		* RailcraftAPI|carts (2.0.0) from Railcraft_1.10.2-10.0.0.jar
		* RailcraftAPI|charge (3.0.0) from Railcraft_1.10.2-10.0.0.jar
		* RailcraftAPI|crafting (2.0.0) from Railcraft_1.10.2-10.0.0.jar
		* RailcraftAPI|events (2.0.0) from Railcraft_1.10.2-10.0.0.jar
		* RailcraftAPI|fuel (2.0.0) from Railcraft_1.10.2-10.0.0.jar
		* RailcraftAPI|helpers (2.0.0) from Railcraft_1.10.2-10.0.0.jar
		* RailcraftAPI|items (2.0.0) from Railcraft_1.10.2-10.0.0.jar
		* RailcraftAPI|locomotive (2.0.0) from Railcraft_1.10.2-10.0.0.jar
		* RailcraftAPI|signals (3.0.0) from Railcraft_1.10.2-10.0.0.jar
		* RailcraftAPI|tracks (3.0.0) from Railcraft_1.10.2-10.0.0.jar
		* SilentGemsAPI (2) from SilentsGems-1.10.2-2.1.4-83.jar
		* StorageDrawersAPI (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.4.6.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.4.6.jar
		* StorageDrawersAPI|event (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.4.6.jar
		* StorageDrawersAPI|inventory (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.4.6.jar
		* StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.4.6.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.4.6.jar
		* StorageDrawersAPI|render (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.4.6.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.4.6.jar
		* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.4.6.jar
		* thut|API (1.0.0) from thutcore-3.8.0.jar
		* totemic|API (2.1.0) from Totemic-1.9.4-0.7.9.1.jar
		* WailaAPI (1.3) from Waila-1.7.0-B3_1.9.4.jar
	Launched Version: forge-12.18.2.2125
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.5.0 NVIDIA 368.81, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x AMD FX(tm)-8120 Eight-Core Processor 
```

**Comment by rubensworks** [comment]
Looks like I did something wrong in the latest CyclopsCore update.
In the meantime, a downgrade to the previous CC version should allow you to use the LP again.
